### ISSUE TITLE
Unable to load SPI in springboot

### ISSUE THREAD

**Issue by crossoverJie** [open-telemetry/opentelemetry-java-instrumentation#10921]
### Describe the bug

When using `java.net.spi.InetAddressResolverProvider`, the custom SPI does not load properly.

### Steps to reproduce

META-INF/services/java.net.spi.InetAddressResolverProvider: `com.example.demo.MyAddressResolverProvider`

```bash
java  -javaagent:opentelemetry-javaagent.jar \
      -jar target/demo-0.0.1-SNAPSHOT.jar
```

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/15684156/4a336837-655a-4dc9-9283-20e96860dcc5)

### Expected behavior

Customized implementation takes effect successfully.

### Actual behavior

Custom implementation does not take effect.

### Javaagent or library instrumentation version

1.32.0

### Environment

**JDK**:21
**OS**: Linux/MacOS

### Additional context

When I use this command (without a javaagent):
```shell
java -jar  target/demo-0.0.1-SNAPSHOT.jar
```

It's work fine.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/15684156/6ce18e35-dde7-4c3a-8106-82e93fbc44e0)

And the classloader is correct: `URLClassPath$Loader@1211`

When I use this command (with javaagent):
```shell
java  -javaagent:opentelemetry-javaagent.jar \
      -jar target/demo-0.0.1-SNAPSHOT.jar
```
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/15684156/d588f93a-243c-41a3-acbf-e0e813719bc6)

The classloader is incorrect: `URLClassPath$JarLoader@814`. The JarLoader cannot load the springboot jar; it can only load the normal Maven project jar.

And this method cannot be called `org.springframework.boot.loader.launch.JarLauncher#main`.

If I don't use Spring Boot instead of a normal Maven project, it'll also work fine.

**Comment by laurit** [comment]
Do I understand correctly that the issue is that because agent tries to establish network connections it will trigger loading `java.net.spi.InetAddressResolverProvider` before spring boot has set up its class loader and because of that your custom implementation of `java.net.spi.InetAddressResolverProvider` won't be used? If that is the case have you considered packaging your `java.net.spi.InetAddressResolverProvider` implementation and the the corresponding `META-INF/services` file in the root of the jar along with spring boot launcher code. I think this way your provider should be found even if the agent triggers initializing the networking code.

**Comment by crossoverJie** [comment]
> If that is the case have you considered packaging your `java.net.spi.InetAddressResolverProvider` implementation and the the corresponding `META-INF/services` file in the root of the jar along with spring boot launcher code.

> in the root of the jar

Thank you for your reply.

Could you please explain in detail how to achieve this?

**Comment by laurit** [comment]
> Could you please explain in detail how to achieve this?

No, I can't, I'm not a spring boot user and don't know exactly how you'd do this. Spring boot questions are best asked from spring boot channels or stack overflow. In your place I'd start by manually modifying the jar and seeing whether it resolves the issue. If it helps I'd check the documentation for spring boot plugin for the build system in use, for example https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#packaging.layers.configuration looks promising.

**Comment by serkan-ozal** [comment]
Hi @laurit @crossoverJie,

As @laurit mentioned, system-wide `InetAddressResolver` in the `InetAddress` is initialized by the OTEL Java agent through system classloader without your custom `InetAddressResolver`. Because your custom `InetAddressResolver` is not visible to system classloader, but Spring Boot's custom classloader.

When I have debug the code, I have seen that `InetAddress` initialization is triggered by `HostResourceProvider` (which calls `HostResource.get()` and then `InetAddress.getLocalHost().getHostName()`).

As a workaround, you can disable `HostResourceProvider`
- by environment variable:
```
OTEL_JAVA_DISABLED_RESOURCE_PROVIDERS=otel.java.disabled.resource.providers.HostResourceProvider
```
- or by system property:
```

-Dotel.java.disabled.resource-providers=otel.java.disabled.resource.providers.HostResourceProvider
```

**Comment by crossoverJie** [comment]
@serkan-ozal Thank you for your reply.

> -Dotel.java.disabled.resource-providers=otel.java.disabled.resource.providers.HostResourceProvider

I have added this system property, but it's not work for me.

I have created a demo [repo](https://github.com/crossoverJie/demo); if you have time, you can give it a try.

**Comment by serkan-ozal** [comment]
@crossoverJie Sorry, it is my bad. I made an error while copy-pasting full classname of the `HostResourceProvider` :)

For the correct workaround, you can disable `HostResourceProvider`

- by environment variable:
```sh
OTEL_JAVA_DISABLED_RESOURCE_PROVIDERS=io.opentelemetry.instrumentation.resources.HostResourceProvider
or by system property:
```
```sh
-Dotel.java.disabled.resource-providers=io.opentelemetry.instrumentation.resources.HostResourceProvider
```

I have tried with your example and verified that it works.

**Comment by crossoverJie** [comment]
@serkan-ozal Thank you for your help. It works for me.

I found `HostResourceProvider` provides the attributes: `host.name` and `host.arch`, I will miss these attributes if I disable it.

Is there any other better solution?

**Comment by Cirilla-zmh** [comment]
> Is there any other better solution?

Seems like the loading of `InetAddressResolver` leads this case. Can you load your `MyAddressResolverProvider` after initialization of agent, and replace the global resolver by reflection?

**Comment by serkan-ozal** [comment]
Hi @laurit 

I think the easiest fix for this issue might be resetting (setting to `null`) `resolver` field of the `InetAddress` class by reflection just after we get the host name in the `HostResource`. So when it is called by the user application later, `InetAddressResolver` will be resolved again through the thread context classloader (or system classloader if not set) and will be able to detect user defined `InetAddressResolver`.

I have tried this solution and verified that it works. However, since we use reflection to set the private `resolver` field of the `InetAddress` class, we need to open `java.base/java.net` module to our agent's module for Java 9+. To do that, I have defined `JavaNetInitializer` class in the `javaagent-tooling-java9` module and `JavaNetInitializer` opens `java.base/java.net` to our agent's module by `ClassInjector.UsingInstrumentation.redefineModule`:
```java
    JavaModule currentModule = JavaModule.ofType(JavaNetInitializer.class);
    JavaModule javaBase = JavaModule.ofType(ClassLoader.class);
    if (javaBase != null && javaBase.isNamed() && currentModule != null) {
      ClassInjector.UsingInstrumentation.redefineModule(
          instrumentation,
          javaBase,
          Collections.emptySet(),
          Collections.emptyMap(),
          Collections.singletonMap("java.net", Collections.singleton(currentModule)),
          Collections.emptySet(),
          Collections.emptyMap());
    }
```

So, if that makes sense for you, I can send a PR for further discussions.

**Comment by Edward-Li** [comment]
Hi @serkan-ozal , i got a similar issue here. 

i am using "openjdk version "17.0.5" 2022-10-18 LTS", and i made exe file with jpackage.

Nomaly i can start and the application works, and i use feign-okhttp to send http request, but after i append the javaagent, there is always an error pop-up with "platform encoding not initialized".  when i check the stack, the error is caused by java.base/java.net Inet6AddressImpl lookupAllHostAddr (Unknown Source)

may be it is similar as what you said,  system-wide InetAddressResolver in the InetAddress is initialized by the OTEL Java agent through system classloader. and i tried to add "-Dotel.java.disabled.resource-providers=io.opentelemetry.instrumentation.resources.HostResourceProvider" to system property, also not works.

PS. this issue not happen when i run javaagent within IDEA debugging mode.

could you help on this? thanks in advance.


and here is the error log, 

Caused by: java.lang.InternalError: platform encoding not initialized
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.ericsson.smi.tina.gui.service.http.TinaFeignFactory$RequestInterceptor.intercept(TinaFeignFactory.java:156)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:182)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:53)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:104)
	at jdk.proxy3/jdk.proxy3.$Proxy85.syncLoginData(Unknown Source)
	at com.ericsson.smi.tina.gui.service.TraceService.loginInfoUpload(TraceService.java:159)
	at com.ericsson.smi.tina.gui.ui.operator.Home.<init>(Home.java:353)

**Comment by Edward-Li** [comment]
i tried several ways to fix, like upgrade my local jre to jdk, upgrade to latest jdk 17, start with debug mode, all not works. 

finally i take a workaround, import dnsjava to my project, and ovreride okhttp3's dns, and working now. but the root cause is still not found, confusing about it, leave a mark here.
