### ISSUE TITLE
java.lang.NoSuchMethodError: reactor.core.publisher.Mono.subscriberContext()Lreactor/core/publisher/Mono;

### ISSUE THREAD

**Issue by GondaliaKaran** [open-telemetry/opentelemetry-java-instrumentation#10997]
### Describe the bug

My java service takes a hit in terms of latency when adding opentelemetry. It works correctly without Otel. 

Below versions are used: 
lettuce : 6.1.10
reactor-core : 3.5.3

Only this exception is being printed in application logs : 

```
throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.NoSuchMethodError: reactor.core.publisher.Mono.subscriberContext()Lreactor/core/publisher/Mono;
	at io.lettuce.core.tracing.Tracing.getContext(Tracing.java:84) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
```

Adding otel autoinstrumentation using the startup args in the java service.

### Steps to reproduce

1. Use lettuce with reactor-core and call redis operations.
2. This should cause lot of exceptions and takes a hit for my api latency and errors

### Expected behavior

No exceptions

### Actual behavior

```
throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.NoSuchMethodError: reactor.core.publisher.Mono.subscriberContext()Lreactor/core/publisher/Mono;
	at io.lettuce.core.tracing.Tracing.getContext(Tracing.java:84) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
```

### Javaagent or library instrumentation version

java sdk : 2.2.0

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
You are using incompatible versions of reactor-core and lettuce, update your lettuce version.

**Comment by GondaliaKaran** [comment]
Thanks @laurit . But this impacts only when otel is enabled. If the versions are incompatible, then ideally this should not work when instrumentation is disabled.

**Comment by GondaliaKaran** [comment]
Got it @laurit . Read more on this and understood how this is affecting my application. Thanks for the details.

**Comment by laurit** [comment]
>  If the versions are incompatible, then ideally this should not work when instrumentation is disabled

This is a totally reasonable assumption. We have safeguards that should prevent applying instrumentation when instrumentation is incompatible with the library used. Here our safeguards don't work because the incompatibility is between the library and its dependency, instrumentation just triggers using the problematic code that isn't used without the instrumentation. I don't know whether there are other code paths that could manifest similar issue without the agent. While it is most likely possible to work around the issue either by disabling the instrumentation when this incompatibility is detected or patching the library code to work correctly even with incompatible dependency this far nobody has stepped up to make the necessary changes.

**Comment by GondaliaKaran** [comment]
Thanks for the details @laurit
