### ISSUE TITLE
move kafka spring starter test to spring smoke test project

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#11261]
so that it can be tested with graalvm native

**Comment by trask** [comment]
Do you think it's possible to run the normal instrumentation tests using native images, or is this a pattern we expect for all library instrumentation (creating smoke tests to test native images)?

**Comment by laurit** [comment]
The title of this issue is misleading. I initially thought that this is about tests in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring/spring-kafka-2.7 but it is really about https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/src/test/java/io/opentelemetry/instrumentation/spring/autoconfigure/instrumentation/kafka/KafkaIntegrationTest.java

**Comment by zeitlinger** [comment]
> The title of this issue is misleading. 

good catch - renamed

**Comment by zeitlinger** [comment]
> Do you think it's possible to run the normal instrumentation tests using native images, or is this a pattern we expect for all library instrumentation (creating smoke tests to test native images)?

@jeanbisutti can you explain?

**Comment by jeanbisutti** [comment]
The potential perspectives:
* Test the automatic instrumentations of the OTel Spring starter in the `smoke-tests-otel-starter` projet, both with a JVM runtime and a GraalVM native one
*  Later, move to real smoke tests in the `smoke-tests-otel-starter` project by using MockServer for example
* Later, add tests in `smoke-tests-otel-starter` with the OTel starter used with instrumentation libraries (not Spring libraries), waiting for automatic instrumentation if the automatic instrumentation is possible (one of the first motivations of the `smoke-tests-otel-starter` project was to avoid regressions when the OTel Starter was used with the OTel log appenders and the JDBC instrumentation library, but both will have automatic instrumentation once #11258 is merged).

We need to verify the OTel starter compatibility with Spring Boot 2 (to detect potential issues with Java 17 code for example), so we would leave some tests in the `spring-boot-autoconfigure` project.
