### ISSUE TITLE
Supporting B3 baggage propagation in Java instrumentation

### ISSUE THREAD

**Issue by wgy035** [open-telemetry/opentelemetry-java-instrumentation#11430]
### Is your feature request related to a problem? Please describe.

B3Propagator doesn't inject baggage as headers, mentioned in https://github.com/open-telemetry/opentelemetry-java/issues/5853

### Describe the solution you'd like

In Java instrumentation, add a new Baggage propagator `B3BaggagePropagator` to inject baggage as headers.

### Describe alternatives you've considered

Although [https://github.com/openzipkin/b3-propagation ](url) does not define baggage propagation, also zipkin has no mandate baggage prefix, but I think it's necessary to implement it in Java instrumentation, and majority users use `baggage-` prefix.

**Comment by laurit** [comment]
Firstly this issue is better suited for [opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib) ([opentelemetry-java](https://github.com/open-telemetry/opentelemetry-java) is for propagators required by otel spec). As what you are requesting is not specified in the b3 spec it would increase the chances of a PR implementing this feature to get merged if you could
- provide description of how this propagator should work
- provide information on who else implements this (who sends and accepts these headers)?

**Comment by wgy035** [comment]
Very helpful suggestions :)  And this issue can be closed, I'd like to create a PR for [https://github.com/open-telemetry/opentelemetry-java-contrib](url)
