### ISSUE TITLE
Save ILoggingEvent.getArgumentArray() arguments from Logback to support structured logging

### ISSUE THREAD

**Issue by igor-suhorukov** [open-telemetry/opentelemetry-java-instrumentation#11861]
### Is your feature request related to a problem? Please describe.

In legacy java application methods like **log.info("Message {}, {} and {}, arg1,arg2,arg3)** often happens in code.
It would be convenient to store such log arguments in telemetry for log search functionality without using full-text search.

### Describe the solution you'd like

Save ILoggingEvent.getArgumentArray() into AttributesBuilder in the existing io.opentelemetry.instrumentation.logback.appender.v1_0.internal.LoggingEventMapper.mapLoggingEvent() and save log message pattern as attribute also. 
Introduce capture-arguments boolean parameter to switch on/off this functionality as part of otel.instrumentation.logback-appender.experimental. and OpenTelemetryAppender

![Screenshot from 2024-07-19 15-44-44](https://github.com/user-attachments/assets/846d0892-faa3-45ff-bcc0-722c3a82375b)

### Describe alternatives you've considered

Use the structured log body for log arguments capture in OpenTelemetry for logback

**Comment by trask** [comment]
> Save ILoggingEvent.getArgumentArray() into AttributesBuilder in the existing io.opentelemetry.instrumentation.logback.appender.v1_0.internal.LoggingEventMapper.mapLoggingEvent() and save log message pattern as attribute also.

we may want to use the structured log body (to be stabilized in Java API soon: https://github.com/open-telemetry/opentelemetry-java/pull/6591) instead of log attributes (similar to recommendation on event body vs event attributes: https://github.com/open-telemetry/semantic-conventions/pull/1263)

maybe we could use `log.body.original` (https://github.com/open-telemetry/semantic-conventions/pull/1217) to store the 

though that may not give the best experience for backends that don't yet understand otel structured log bodies or `log.body.original`

(fyi @djaglowski @tigrannajaryan @jack-berg)

**Comment by igor-suhorukov** [comment]
@trask it sounds reasonable. But before full support of structured log body in OpenTelemetryAppender I would like to have a working solution for arguments. I can provide PR for logging arguments
