### ISSUE TITLE
Tomcat7 and Tomcat 10 instrumenter may appear at the same time

### ISSUE THREAD

**Issue by halleystar** [open-telemetry/opentelemetry-java-instrumentation#11912]
### Describe the bug

Tomcat7 and Tomcat 10 instrumenters may appear at the same time, causing some metrics to fail to be exported properly.

### Steps to reproduce

1.  use springboot  3.2.5 which will import tomcat-10.0
2.  use javax.servlet-api which will import class `javax.servlet.http.HttpServletRequest`
3. request a springboot uri then  check the metrics.
4. some metric like http.server.request.duration will be lost

### Expected behavior

no  metrics to fail to be exported

### Actual behavior

some metrics to fail to be exported properly

### Javaagent or library instrumentation version

2.6.0

### Environment

**JDK**:
**OS**:

### Additional context

![QQ_1722251570814](https://github.com/user-attachments/assets/7cf216de-7c88-4b74-8e7d-6d1db1e7e4f7)
Can we add the content in the red box in the picture to solve this issue? If so, I would like to make a pr

**Comment by trask** [comment]
hi @halleystar! would this could cause problems for Tomcat 9 users who happen to (accidentally) have jakarta artifact dependency?

do you think we could target specific Tomcat classes that are only present/absent in Tomcat 10, to better target the instrumentation at those versions instead of relying on javax/jakarta classes?

**Comment by halleystar** [comment]
![QQ_1722303696455](https://github.com/user-attachments/assets/2f56d718-abe0-4250-b1a3-37264d3bcaac)
In tomcat 10, jakarta.servlet.http.HttpServletRequest is used. Isn't it specific to tomcat 10?

**Comment by laurit** [comment]
I guess you run into this because you include javax.servlet api in your spring boot 3 application which you probably shouldn't. The fix you proposed isn't ideal because if a spring boot app using tomcat bundles both javax and jakarta servlet api then the tomcat instrumentation would be disabled. Perhaps we could come up with something better that could more reliably distinguish tomcat 10 from earlier versions.

**Comment by halleystar** [comment]
Because some third-party jars are still using javax.servlet-api, the possibility of coexistence of springboot 3 and javax.servlet-api is still very high
