### ISSUE TITLE
Memory leak in netty4.1 io.netty.channel.socket.nio.NioSocketChannel

### ISSUE THREAD

**Issue by starsliao** [open-telemetry/opentelemetry-java-instrumentation#11942]
I  encountered the issue of memory leaks with Netty. I am using version 2.5.0 of autoinstrumentation-java, and I have experienced the same problem.

In long-running Java microservices (running for more than 20 days，high volume of requests), there is insufficient Java heap memory. Many microservices are experiencing this issue, and some of these microservices are not even using Netty.

I previously had the same issue when using version 2.3.0 of autoinstrumentation-java.

[This is latest Java dump file.](https://ops-logs.obs.cn-south-1.myhuaweicloud.com:443/deploy-product-diagnosis-service-6c59c89bc4-h58fh.zip?AccessKeyId=CSIE3Z1KY33LJLF9NAI9&Expires=1722858227&x-obs-security-token=ggpjbi1ub3J0aC00TeN7ImFjY2VzcyI6IkNTSUUzWjFLWTMzTEpMRjlOQUk5IiwibWV0aG9kcyI6WyJ0b2tlbiJdLCJyb2xlIjpbXSwicm9sZXRhZ2VzIjpbXSwidGltZW91dF9hdCI6MTcyMjg1ODIxMDU2MywidXNlciI6eyJkb21haW4iOnsiaWQiOiIwYTc5YjRmOWE0MDAyNmU3MGZlMGMwMTI2M2Q0YjcwMCIsIm5hbWUiOiJjYXNzbWFsbCJ9LCJpZCI6IjBhNzliNGZhNWE4MDI2ZTAxZjFjYzAxMmNlNTljNzkyIiwibmFtZSI6ImNhc3NtYWxsIiwicGFzc3dvcmRfZXhwaXJlc19hdCI6IjIwMjQtMTEtMTZUMDE6NDE6MDAuMDAwMDAwWiIsInVzZXJfdHlwZSI6MTd9fXMf8V63puf9c1IlYBPfk_K55B0U5O5xhDYaxVo49P-Jw94Jrsw7xvS8tEX7L0OfM3Jbs4XS8jOUEv-ddS2pYFWp6Y9eeJM-NHHh_cnAjo-3BoQP-1BcXF9AtD37AlQPD6fWhyS7_Oyd9S2-fqwcRS3krxDyAC-aqdi9zYvI2VBVG5aMKfDnqs5uy5dzlDnqcp1CITJNRdRVIouBaAonBkd7iO8ymJ_cP749kLs1IneggGFaB-jGl6tdgsrZHlche1-cWD7zWbfQlRjA1vn-nN3q995Opb5d3Hwxwd8v8RCZD80tMh0RCq-8SJdCIaOF5R6r832A5eFFHtQEr3RxiiU%3D&Signature=ZfUDl2zkzhdDJ/t0zcfxSciWbb8%3D)

I am an operations engineer, and this is the phenomenon I observed. Below is the screenshot information provided by my development colleagues.

<img width="1069" alt="企业微信截图_17200595874833" src="https://github.com/user-attachments/assets/d054af11-00b4-4881-bb22-9175fa036492">
![企业微信截图_17200793969702](https://github.com/user-attachments/assets/c98fd2f7-633e-40e3-8b36-3ac1676d21b2)
<img width="730" alt="企业微信截图_17200797606265" src="https://github.com/user-attachments/assets/689161b4-737e-4b4e-a0af-55cb97024906">

![企业微信截图_17200793969702](https://github.com/user-attachments/assets/bced84af-c8d0-45b5-acbe-65d3cc4981e9)

_Originally posted by @starsliao in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11399#issuecomment-2267608218_

**Comment by laurit** [comment]
Is this a custom http server implemented on top of netty? Or are you using some framework. As far as I can tell there are a couple of long running connections that have processed a lot of requests. Connections that don't serve too many requests shouldn't cause this issue as the stale data would get cleaned when the connection is closed. Probably the issue is in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ade7c8072031a5a7fb284695b07059db6949ac1a/instrumentation/netty/netty-4.1/library/src/main/java/io/opentelemetry/instrumentation/netty/v4_1/internal/server/HttpServerResponseTracingHandler.java#L53 where server contexts are removed and spans are ended only on certain inputs to the `write` method. It would help to know what the server code is sending to the write method.

**Comment by laurit** [comment]
I think it is actually xxl-remoting not xxl-job that triggers the issue. What version of xxl-remoting are you using.

> Could opentelemetry-java-instrumentation be optimized for such a long connection scenario? Or are there any other ways to avoid this problem?

Sure, we gladly accept pull requests that fix issues.

**Comment by laurit** [comment]
It is actually called [xxl-rpc](https://github.com/xuxueli/xxl-rpc) not xxl-remoting.

**Comment by laurit** [comment]
I think this happens because of https://github.com/xuxueli/xxl-rpc/blob/eeaa1bd7fc8f2249de13f971dda4f6689d66f318/xxl-rpc-core/src/main/java/com/xxl/rpc/core/remoting/net/impl/netty_http/server/NettyHttpServerHandler.java#L85-L88 There is no response for heartbeat requests. Our assumption is that every request has a matching response. When there is a request without a response we'll miss cleaning up.
