### ISSUE TITLE
Logback MDC auto-instrumentation gets muzzled and does not work

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1201]
I've prepared a simple console app that helps reproduce this issue: https://github.com/mateuszrzeszutek/test-console-app
I tested both 0.8.0 and master branch -- auto-instrumentation does not work on both of them.

When you run it with debug logs you'll see the following message:

```
[opentelemetry.auto.trace 2020-09-14 16:26:09:885 +0200] [main] DEBUG io.opentelemetry.javaagent.tooling.Instrumenter$Default - Instrumentation muzzled: [logback] -- io.opentelemetry.instrumentation.auto.logback.v1_0_0.LogbackInstrumentation on jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15
[opentelemetry.auto.trace 2020-09-14 16:26:09:885 +0200] [main] DEBUG io.opentelemetry.javaagent.tooling.Instrumenter$Default - -- io.opentelemetry.javaagent.shaded.instrumentation.logback.v1_0_0.LoggingEventWrapper:100 Missing method getMarker#()Lio/opentelemetry/javaagent/slf4j/Marker;
```

and `traceId`, `spanId` and `traceFlags` won't be added to the MDC.

**Comment by iNikem** [comment]
What happens if you remove sfl4j dependency and use the one brought by logback itself?

**Comment by mateuszrzeszutek** [comment]
I think it still won't work - it shouldn't really matter which one you compile against as long as you relocate it later (shadowJar task):

```
  relocate 'org.slf4j', 'io.opentelemetry.javaagent.slf4j'
```

I think it probably needs the same treatment as OTel API -- i.e. prefixing and "unshadowing" packages:

```
  relocate "application.io.opentelemetry", "io.opentelemetry"
```

**Comment by trask** [comment]
> I think it probably needs the same treatment as OTel API -- i.e. prefixing and "unshadowing" packages

👍

Another option (because I know @iNikem dislikes this option 😁), is to rework the logback instrumentation a bit to get rid of the `LoggingEventWrapper` class (which is what's pulling in the slf4j Marker dependency).

You could remove `LoggingEventWrapper`, and instead add a field to `ILoggingEvent` implementations in order to store the updated `mdcPropertyMap`:

  @Override
  public Map<String, String> contextStore() {
    return singletonMap("ch.qos.logback.classic.spi.ILoggingEvent", "java.util.Map");
  }

and then you could add instrumentation on `ILoggingEvent.getMDCPropertyMap()` to return the updated `mdcPropertyMap` if it's not null.

Ping me if you want to go this route and run into any questions.

**Comment by mateuszrzeszutek** [comment]
Actually now that I think of it shadowing isn't really a viable solution for the manual instrumentation lib: we can't really publish an artifact using shaded slf4j, and it doesn't work in auto instrumentation if it's not shaded. We'd have to copy-paste the whole thing to make it work.

I think that your solution might be the only sensible way to make both manual and auto instrumentation work.
