### ISSUE TITLE
Flaky test - :instrumentation:jms-1.1:test

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1206]
I've seen this test fail a lot lately - it does get retried but fails every one of them from what I can tell.

https://gradle.com/s/geylzhj6543j2

**Comment by iNikem** [comment]
I have a strong suspicion that test fails because three separate tests try to run `new EmbeddedActiveMQBroker()`, leading to port conflicts and, potentially, JMX conflicts if run inside one JVM.

The obvious solution hypothesis is to migrate them to testcontainers. But CircleCI does not support them. And we are not ready for #678 because GHA are still too slow. And it is slow, IMO, because we still did not get Gradle cache properly working probably because of #981. In addition, muzzle is VERY slow on GHA right now.

**Comment by anuraaga** [comment]
I didn't think #981 is a priority but if it seems significant can take a look at it now. What makes you suspect it affects caching? I thought it should always have the same value and not affect downstream tasks.

**Comment by iNikem** [comment]
I tried to debug my local build in order to understand why it does not reuse cached results from nightly build for test tasks. Hashes related to bootstrap jar have kept changing. I am not 100% sure what exactly does not work there, but it is certainly related to bootstrap jar.

Nightly build currently prints a lot of debug info for gradle cache, so it is quite easy to verify.

**Comment by anuraaga** [comment]
Going to look into caching - that said, the build was pretty stable for a while and suddenly started failing every day. Did we make a change that affected the build?
