### ISSUE TITLE
Add instructions on how to debug agent

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1241]
I could not find any instructions on how to debug the agent with a running application. 

By running the following code I was able to debug the app, but the breakpoints in the agent were never triggered e.g. in `TracerInstaller`.

```bash
OTLP_EXPORTER=otlp java -javaagent:/home/ploffay/tmp/opentelemetry-javaagent-0.8.0-all.jar -jar -agentlib:jdwp="transport=dt_socket,server=y,suspend=y,address=5000" app.jar
```

**Comment by trask** [comment]
Hey @pavolloffay!

IIRC the debugger isn't attached in time for premain stuff, e.g. javaagent initialization like `TracerInstaller`.

The other issue to watch out for with debugging is that breakpoints won't work inside of `@Advice.OnMethodEnter` and `@Advice.OnMethodExit` methods, because those methods are inlined by bytebuddy into the instrumented methods.

**Comment by pavolloffay** [comment]
Is there anything we can do about this? 

I can at least document this in the contributing docs.

**Comment by anuraaga** [comment]
#482 may be related - while it might not help with `TracerInstaller` it can let the actual instrumentation code be debugged which still helps a lot.
