### ISSUE TITLE
run test fail. Unsupported version of junit:junit: 4.11-SNAPSHOT-20120805-1225

### ISSUE THREAD

**Issue by misaya98** [open-telemetry/opentelemetry-java-instrumentation#12539]
### Describe the bug

when clone the code to local pc, and run the main branch test , i got this error. how can i fix it?
i run the JarServiceNameDetectorTest.java
![image](https://github.com/user-attachments/assets/5d3c92a3-61e3-4035-9c4e-bd0fe00a50d8)

### Steps to reproduce

run the main branch 's JarServiceNameDetectorTest

### Expected behavior

JarServiceNameDetectorTest run success

### Actual behavior

unit test fail

### Javaagent or library instrumentation version

main

### Environment

**JDK**: 11
**OS**: windows 11

**Comment by misaya98** [comment]
> Did you run the test from command line or intellij?

intellij , should i use command line ?

**Comment by laurit** [comment]
> intellij , should i use command line ?

since this issue affects only you you are the only person that can debug it. Trying command line could help you to narrow down the issue. If it also fails from the command line then looking at the dependency tree might help. Perhaps it is possible to figure out where the old junit dependency comes from. If it only fails in intellij then I'd suggest downloading the latest intellij and seeing if that changes anything.

**Comment by wl2027** [comment]
@laurit Hi, I have reproduced this issue. It was caused by using a custom Maven mirror, such as `maven { url = uri("https://repo.huaweicloud.com/repository/maven/") }`. The solution is simple: just remove the custom Maven repository and use the official one.
