### ISSUE TITLE
Reduce calls to Context.current()

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1265]
Currently, we typically do something like:
```
span = TRACER.startSpan(request);
scope = TRACER.startScope(span);
```
This ends up looking up `Context.current()` twice.

It would be (ever so slightly) faster, and more explicit about context management, to do something like:
```
Context context = Context.current();
span = TRACER.startSpan(context, request);
scope = TRACER.startScope(context, span);
```

**Comment by iNikem** [comment]
But this again increases the API surface

**Comment by iNikem** [comment]
Can you remind me, why do you prefer explicit and separate scope management by default?

**Comment by trask** [comment]
> But this again increases the API surface

ya, this would be a good reason not to do this

> Can you remind me, why do you prefer explicit and separate scope management by default?

because when it's not explicit, context management borderlines on magical, and it's easy to forget what's really happening

E.g. when I see this code:

```
span = TRACER.startSpan(request);
scope = TRACER.startScope(span);
```

I keep thinking that `startSpan` captures the current context as part of the span, and then `startScope` uses the context that was captured by the span

**Comment by anuraaga** [comment]
Also while increasing thread local lookup from 1 to 2 is basically nothing, one thing to keep in mind is 100 to 200 becomes significant - I heard a lot of work was needed on Sleuth to reduce context mounting due to the overhead of thread local and remounting on every op in a reactive stream. This was because user apps were getting affected, not just theory.

That doesn't mean all of our usage will trigger such asymptotic behavior but a general stance of avoiding thread local lookup is safer than one where we always go with implicit linking because of these cases.

**Comment by trask** [comment]
I ran into several cases in #1350 where we are putting Context into scope unnecessarily, which could be improved by passing Context as an argument to `startSpan`
