### ISSUE TITLE
Finalize package name and artifact name for WithSpan

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1369]
Currently:
* package name is `io.opentelemetry.extensions.auto.annotations`
* artifact name is `io.opentelemetry:opentelemetry-extension-auto-annotations`

I think this might be better long-term:
* package name `io.opentelemetry.instrumentation.annotations`
* artifact name `io.opentelemetry.instrumentation:instrumentation-annotations`

Note, `WithSpan` is being used by both javaagent instrumentation spring library instrumentation.

**Comment by iNikem** [comment]
@trask so you suggest moving it from open-telemetry/opentelemetry-java repo to here?

**Comment by trask** [comment]
yes, I think it makes sense under `io.opentelemetry.instrumentation` package, which would mean moving it to this repo

cc: @jkwatson in case any thoughts

**Comment by iNikem** [comment]
I don't fully understand how to do that. We should publish `WithSpan` separately from `WithSpanAnnotationInstrumentation` and related code. So that clients can depend on only one class that they need. This artifact containing `WithSpan` annotation cannot live under `instrumentation` module, because it is neither agent instrumentation not library instrumentation (as it is useless without actual agent).

One option is to introduce new `extensions/annotations` module.

But writing all this made me think: is `io.opentelemetry.instrumentation:instrumentation-annotations` a correct artifact name to contain just this annotation after all? I mean `instrumentation` part of it.

**Comment by jkwatson** [comment]
It definitely needs to be published as consumable outside the agent. I thought we had been waiting until y'all had gotten your maven-central story straight before moving it.

**Comment by iNikem** [comment]
We talked about this issue last week and decide it still makes sense to have in SDK repo, and not agent repo. Created open-telemetry/opentelemetry-java#2055 to track package change.
