### ISSUE TITLE
Muzzle requires java 11

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1402]
Running muzzle task on JDK8 results on error:

```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':instrumentation:servlet:servlet-3.0:muzzle-AssertPass-javax.servlet-javax.servlet-api-4.0.0'.
> No such property: platformClassLoader for class: java.lang.ClassLoader
```

Does anybody know about this limitation or how to fix it? We should at least document it.

**Comment by mateuszrzeszutek** [comment]
Hmm, I think that we should try to use the same logic as in `AgentInitializer`:

```java
    if (isJavaBefore9()) {
      agentParent = null; // bootstrap
    } else {
      // platform classloader is parent of system in java 9+
      agentParent = getPlatformClassLoader();
    }
```

and use bootstrap classloader instead.

**Comment by pavolloffay** [comment]
I could give it a try

**Comment by anuraaga** [comment]
For agent we only support building with Java 11, I thought that was documented somewhere. I'm surprised anything works on Java 8 :)

**Comment by iNikem** [comment]
I don't think we should support building on java 8.

**Comment by pavolloffay** [comment]
> I don't think we should support building on java 8.

Are there any specific reasons? We should document this with some rationale.

**Comment by anuraaga** [comment]
Runtime fixes are often backported but compiler fixes rarely are. For example, Java 8 doesn't support the excellent `-release` flag or richer javadoc.

Now that Gradle 6.7 let's us have full control of the Java used with building by going so far as to only support the latest version of Java released at the time - it'll have all the latest compiler features with basically no downside since Gradle itself would still run regardless of Java version. I can go ahead and write this up in rationale along with the 6.7 upgrade soon :)

**Comment by iNikem** [comment]
Support only the latest version is a little bit too extreme for me :) But I will not object to this, if you really want it. Current LTS seems like a sensible middle ground.

**Comment by iNikem** [comment]
Our [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/CONTRIBUTING.md) says:

> In order to build and test this whole repository you need JDK 11+

As we want to keep that way, I think this task can be closed.
