### ISSUE TITLE
gRPC TracingClientInterceptor goes against gRPC recommendation

### ISSUE THREAD

**Issue by asarkar** [open-telemetry/opentelemetry-java-instrumentation#1434]
@ejona86 said in [this comment](https://github.com/grpc/grpc-java/issues/7415#issuecomment-692886506):

> We discourage ClientInterceptors from modifying Context, as that mutation will be visible in StreamObserver callbacks which may then perform additional RPCs and then you get into a confusing situation. If the application itself modifies the context before calling the stub, then it is obvious the context will have those modifications for the callbacks and newCall() or start() have the same context exposed to them.

However, that's exactly what happens in [TracingClientInterceptor.interceptCall](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/grpc-1.5/library/src/main/java/io/opentelemetry/instrumentation/grpc/v1_5/client/TracingClientInterceptor.java#L62).
> Context context = withSpan(span, Context.current());

I'm not a gRPC expert and not sure yet what the alternative might be since the code using the stub doesn't have access to the headers.

**Comment by anuraaga** [comment]
@asarkar Thanks for the note - yeah I don't see a way around it unfortunately. Apparently there is a more official way of tracing, but didn't get a response in it becoming a stable API, until which we can't really use it https://github.com/grpc/grpc-java/issues/2861#issuecomment-703998728

**Comment by asarkar** [comment]
@anuraaga Napoleon said: "If you want a thing done well, do it yourself." That's especially golden is the OSS world. 😄

**Comment by ejona86** [comment]
I don't see how using a gRPC tracer solves the issue discussed here. The gRPC tracer is for low-level stream details, which is intended for _stats_. It could be used for tracing as well, but the choice relates to how retries should be handled and not an API restriction.

There doesn't appear to be much purpose to attaching the context to the current thread, so the solution seems to be as simple as "don't."

**Comment by ejona86** [comment]
Note: it would be possible to "restore"/"unwrap" the original context in the listener, but that requires being aware of all callback possibilities which would break when new callbacks are added.

**Comment by anuraaga** [comment]
@ejona86 Oops sorry I assumed client tracer has the `filterContext` like the server one does without the mentioned caveats but didn't actually look at the javadoc, my bad. Bogdan had suggested once we should be using the tracers, mainly for that method.

We want to be able to put the span inside the gRPC Context since that would allow them to use gRPC context propagation mechanisms like `Context.wrap` and tracing gets propagated together - it decouples context propagation in their app from what tracing system they use. Is this just not supported by gRPC for client calls?

**Comment by ejona86** [comment]
> Bogdan had suggested once we should be using the tracers, mainly for that method.

That method is _only_ necessary for a server tracer. For an `ServerInterceptor`, you can modify the Context on server-side and then use the convenience [`Contexts.interceptCall()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/Contexts.html#interceptCall-io.grpc.Context-io.grpc.ServerCall-io.grpc.Metadata-io.grpc.ServerCallHandler-).

> We want to be able to put the span inside the gRPC Context since that would allow them to use gRPC context propagation mechanisms like Context.wrap and tracing gets propagated together - it decouples context propagation in their app from what tracing system they use. Is this just not supported by gRPC for client calls?

It's 100% supported. You can read the Context without issue in a `ClientInterceptor`. All we're suggesting is don't replace the context from an interceptor. There's no point to that because nothing should be reading the tracing information from the context past your interceptor. In the rarer case you need to communicate with an interceptor, we recommend using CallOptions.Key.

**Comment by trask** [comment]
@anuraaga is this resolved by the recent gRPC context bridge work?

**Comment by anuraaga** [comment]
@trask Think so
