### ISSUE TITLE
Activate SystemMetrics

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java-instrumentation#1508]
- `SystemMetrics.registerObservers()` should be called if `oshi-core` dependency is present.
- `IntervalMetricReader` should be configured to send metrics, if not done already.
- Because of shading looks like there is no was to call `SystemMetrics.registerObservers()` manually

**Comment by malafeev** [comment]
If it's not a high priority then I would like to help on this issue if anybody can provide me guidance.

**Comment by malafeev** [comment]
@anuraaga do you have any idea how to implement it? From last SIG I got more questions than directions.

**Comment by malafeev** [comment]
please assign issue to me

**Comment by anuraaga** [comment]
@malafeev Sorry for the late reply. Discussed with @trask and we think an approach where we add a mechanism to the agent to register a classloader matcher and a callback (essentially an injected helper with a static initializer) would work well for this. Since this is a complicated change, @trask mentioned he could take a stab early next week. Does that work for you?

**Comment by trask** [comment]
hey @malafeev, ping me next week (after Mon), and I will try to outline how this could work

**Comment by malafeev** [comment]
@trask @anuraaga I came with one idea, submitted draft PR: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1530
