### ISSUE TITLE
gRPC metrics

### ISSUE THREAD

**Issue by asarkar** [open-telemetry/opentelemetry-java-instrumentation#1651]
OpenCensus has some [gRPC metrics](https://opencensus.io/guides/grpc/java/#instrumentation). I believe OTEL metrics is still very much a WIP, so what is the recommendation for projects that want to generate metrics? Some options are:

1. Use OpenCensus and bridge (is there one?) to OTEL.
2. Create your own using whatever library you like. This is what I did for [grpc-learning](https://github.com/asarkar/kotlin/tree/master/grpc-learning) using [Micrometer](https://micrometer.io/).
3. ???

**Comment by asarkar** [comment]
@anuraaga Any thoughts?

**Comment by anuraaga** [comment]
Hi @asarkar - currently our focus has been completely on tracing and metrics will still take some time. We don't have any bridging for the metrics either - but I guess you can just use the OpenCensus support from gRPC without worrying about OpenTelemetry? Though currently I would generally recommend Micrometer as it's more mature in the Java ecosystem, but it looks like the gRPC instrumentation for it is also WIP https://github.com/micrometer-metrics/micrometer/pull/2323. Don't have a better answer unfortunately.

This is somewhat of a plug, but you may be interested in taking a look at [Armeria](https://armeria.dev/). It supports hosting gRPC services, along with any other type of service, and has metrics support out of the box for it via micrometer. It's my go-to framework which is why I rarely run into issues :)

**Comment by asarkar** [comment]
Closing, using Micrometer metrics.
