### ISSUE TITLE
Move jetty QueuedThreadPool instrumentation from executors to jetty module

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1912]
And then I think we can delete `NonStandardExecutorInstrumentationModule`.

Inspired by #1897

**Comment by breedx-splk** [comment]
Since the `JavaExecutorsInstrumentation.SetExecuteRunnableStateAdvice` is used by both the nonstandard jetty `QueuedThreadPool` and other executors instrumentation, would you see this creating a cross-instrumentation dependency (is that a thing?) or would you expect the instrumentation to be copied?  

Is there a strategy for instrumentation modules to share code easily?

**Comment by trask** [comment]
ya, I think copied is ok, similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/spring/spring-core-2.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/spring/core/SimpleAsyncTaskExecutorInstrumentation.java
