### ISSUE TITLE
Servlet span names are not always low cardinality

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1954]
See @laurit's comment https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1929#discussion_r546775932

> Note that `request.getServletPath()` isn't always low cardinality.
If servlet is mapped to / then `getServletPath` for request to /foo/bar/baz is /foo/bar/baz. Default servlet that serves static content is typically mapped to /
If servlet is mapped to *.html then `getServletPath` for request to /foo/bar/baz.html is /foo/bar/baz.html.

Any ideas what we can do, short of mapping all servlet requests to `HTTP [METHOD]` (and hope that the application is using a controller routing framework that we instrument so the name will get updated to something better)?

**Comment by trask** [comment]
another related reference point: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1929#discussion_r546650940

**Comment by anuraaga** [comment]
> Any ideas what we can do, short of mapping all servlet requests to HTTP [METHOD] (and hope that the application is using a controller routing framework that we instrument so the name will get updated to something better)?

This option seems ok to me.

**Comment by iNikem** [comment]
All servlet requests - no, I don't like it :) I believe in the past we had servlets producing spans with name `ServletClass.servletMethod`, did we change that? Why?

**Comment by trask** [comment]
I like url-based span names 😄. `FilterClass.doFilter` / `ServletClass.service` / `ServletClass.doX` sound reasonable since we can't use `servletPath`.

**Comment by vovencij** [comment]
Naive implementation will always end with the outermost filter name, e.g. `AuthorizationFilter.filter` for everything. Doesn't look too useful. I'd suggest defaulting to inner-most servlet/filter class name. That one maybe will hint to a MVC framework at least.

**Comment by trask** [comment]
any thoughts what to do with `contextPath` (if anything)?

**Comment by iNikem** [comment]
So, let's take it apart, shall we? :) Based on the assumption that we cannot use actual request url as span name due to its high cardinality.

First, we may have application server integration, which creates SERVER span. This has only 2 options for span name: `HTTP [METHOD]` and `Class.method`.

Then we have Servlet API, which may either create span or update existing span name. If we cannot use `servletPath` as per comments above, then our options are again `HTTP [METHOD]` and `Class.method`. The former potentially can use non-root `contextPath` as well, eg. `HTTP GET /app`. In case of `Class.method` we can use either the first in the chain (as was before) or the last (as suggested by @vovencij ).

Then we may have some controller framework which, presumably, knows a good name.

In case of application server I have to agree that `HTTP [METHOD]` looks like a better option.

In case of Servlet API I proposed in the past to use `Class.method` with the assumption that in case of purely servlet-based application the name of the servlet actually has a meaning. This assumption plays nicely with @vovencij 's suggestion about "last wins". If we disregard this assumption, then `HTTP [METHOD] [contextPath]` is also good.

**Comment by laurit** [comment]
For app server integration I prefer `HTTP METHOD` over `Class.method` because the latter really produces names that are in whiskey-tango-foxtrot category from the end user perspective. Names like `coyoteadapter.service` really don't give any useful information over `HTTP METHOD`.

Whether app server can add `context path` to span name when span is created really depends on exactly where the span is create. On some servers `context path` might not be available at that point, but it is always possible to update the name when `context path` becomes know.

With app server integration we could figure out the mapping that matches current request and use that. This would keep everything almost the same as it is now, the only exceptions would be urls that use a starting wildcard (`*.xxx`) and `/`. As far as I understand there is no way to do this with just servlet api.

Using `HTTP METHOD` for all servlet requests is pretty bad because it will be impossible to distinguish requests, `Class.method` could be slightly better in that regard. Though as previously mentioned if we are going with `Class.method` we should exclude filters because they are likely to be generic or even worse can come from application server. `Class.method` from filter is likely to be as useless as a name as `HTTP METHOD` but just more confusing. For example on tomcat all request would be named `WsFilter.doFilter`. Just using `@Advice.Origin Method method` for servlets would also not fly as most servlets would report as `HttpServlet.service` so I guess we would need to get class name from `@Advice.This Object target`. As an alternative we could consider using `getServletConfig().getServletName()` though when using `@WebServlet` without specifying name it should default to full class name, would that be ok?

Would it be enough if we added integration with app servers to get the request mapping and when there is no app server integration left things as they are?

**Comment by iNikem** [comment]
> For app server integration I prefer `HTTP METHOD` over `Class.method` because the latter really produces names that are in whiskey-tango-foxtrot category from the end user perspective. Names like `coyoteadapter.service` really don't give any useful information over `HTTP METHOD`.

Agree.

 
> Whether app server can add `context path` to span name when span is created really depends on exactly where the span is create. On some servers `context path` might not be available at that point, but it is always possible to update the name when `context path` becomes know.

You mean by another app server specific instrumentation?

> Using `HTTP METHOD` for all servlet requests is pretty bad because it will be impossible to distinguish requests, `Class.method` could be slightly better in that regard. Though as previously mentioned if we are going with `Class.method` we should exclude filters because they are likely to be generic or even worse can come from application server. `Class.method` from filter is likely to be as useless as a name as `HTTP METHOD` but just more confusing. For example on tomcat all request would be named `WsFilter.doFilter`. Just using `@Advice.Origin Method method` for servlets would also not fly as most servlets would report as `HttpServlet.service` so I guess we would need to get class name from `@Advice.This Object target`. As an alternative we could consider using `getServletConfig().getServletName()` though when using `@WebServlet` without specifying name it should default to full class name, would that be ok?

I think this is a very good idea. Both ignoring filters and using servlet name. Full class name is also fine, especially if we abbreviate/remove package.

> 
> Would it be enough if we added integration with app servers to get the request mapping and when there is no app server integration left things as they are?

Either this or improve servlet naming as per previous section.

**Comment by vovencij** [comment]
Ignoring Filters is not nice, because some frameworks (e.g. Struts: https://mkyong.com/struts2/difference-between-struts-2-filterdispatcher-and-strutsprepareandexecutefilter/) are request-mapped using only filters. Generally one cannot assume, that there will servlet at all.

**Comment by iNikem** [comment]
Can "last one wins" solve this problem automatically? Meaning that the last servlet instrumentation will set the name

**Comment by vovencij** [comment]
> Can "last one wins" solve this problem automatically? Meaning that the last servlet instrumentation will set the name

Yes.

**Comment by laurit** [comment]
> > Whether app server can add `context path` to span name when span is created really depends on exactly where the span is create. On some servers `context path` might not be available at that point, but it is always possible to update the name when `context path` becomes know.
> 
> You mean by another app server specific instrumentation?
>
Yes 
> > Using `HTTP METHOD` for all servlet requests is pretty bad because it will be impossible to distinguish requests, `Class.method` could be slightly better in that regard. Though as previously mentioned if we are going with `Class.method` we should exclude filters because they are likely to be generic or even worse can come from application server. `Class.method` from filter is likely to be as useless as a name as `HTTP METHOD` but just more confusing. For example on tomcat all request would be named `WsFilter.doFilter`. Just using `@Advice.Origin Method method` for servlets would also not fly as most servlets would report as `HttpServlet.service` so I guess we would need to get class name from `@Advice.This Object target`. As an alternative we could consider using `getServletConfig().getServletName()` though when using `@WebServlet` without specifying name it should default to full class name, would that be ok?
> 
> I think this is a very good idea. Both ignoring filters and using servlet name. Full class name is also fine, especially if we abbreviate/remove package.
> 
From the name we don't really know whether it is default name or given by user. We could compare servlet name with servlet class name and if they are the same then chop off the package name.

**Comment by laurit** [comment]
> > Can "last one wins" solve this problem automatically? Meaning that the last servlet instrumentation will set the name
> 
> Yes.

Figuring out the innermost filter could be tricky because request dispatcher could forward which would run filters that are configured for forwarding. Or you could just call some servlet or filter directly at some random place.

**Comment by iNikem** [comment]
> > > Can "last one wins" solve this problem automatically? Meaning that the last servlet instrumentation will set the name
> > 
> > 
> > Yes.
> 
> Figuring out the innermost filter could be tricky because request dispatcher could forward which would run filters that are configured for forwarding. Or you could just call some servlet or filter directly at some random place.

Do we need to figure that out? Or is it enough just to always update the name. Then the last will automatically win, no?

**Comment by laurit** [comment]
> Do we need to figure that out? Or is it enough just to always update the name. Then the last will automatically win, no?
In some applications last servlet could be something like common/footer.jsp so I don't think we can just use the last one.

**Comment by laurit** [comment]
Actually there is a way to get mappings with servlet3 api. `servlet.getServletContext().getServletRegistration(servlet.getServletConfig().getServletName()).getMappings();` returns a collection of mappings for given servlet. We could match these mappings against current request and use the first matching mapping as span name.
