### ISSUE TITLE
Http attributes are missing in traces for struts

### ISSUE THREAD

**Issue by shashank11p** [open-telemetry/opentelemetry-java-instrumentation#2126]
**Describe the bug**
There are no http attributes in the traces for struts2

**Steps to reproduce**
Run a struts2 app with the javaagent, and see the exported traces. 

My app is attached. You can run this app and then curl `localhost:1234/context/success`. 
[struts-app.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/5879769/struts-app.zip)

**What did you expect to see?**
Expected to see http attributes in span. 

**What did you see instead?**
There was no span with http attributes, only one span with these tags: 
<img width="1790" alt="Screenshot 2021-01-27 at 4 30 59 PM" src="https://user-images.githubusercontent.com/74622220/105982303-1c9bf380-60bd-11eb-9363-eb5afbd1a529.png">

**What version are you using?**
org.apache.struts:struts2-core:2.3.1

**Comment by laurit** [comment]
Your problem is in `runtimeOnly("javax.servlet", "jsp-api", "2.0")` this depends on javax.servlet:servlet-api:2.4. In the final fat jar you have classes from servlet 3 api and servlet 2.4 api which confuses our integration. servlet-2.2 integration doesn't start because it finds servlet 3 classes, servlet-3.0 integration doesn't start because the classes it finds are from servlet-2.4 and don't contain the require methods. Try using `runtimeOnly("javax.servlet.jsp", "jsp-api", "2.2")` (also you shouldn't need `runtimeOnly("javax.servlet", "javax.servlet-api", "3.0.1")`)

**Comment by shashank11p** [comment]
Thanks. It worked with your suggestion.
