### ISSUE TITLE
Check if JdbcMaps.preparedStatements is still needed (after SQL cache gets merged)

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2127]
`JdbcMaps.preparedStatements` stores the same data as the SQL cache introduced in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2094 - maybe we can remove it (and use a bit less memory)?
We should run some performance tests with & without it (@breedx-splk's petclinic suite?)

**Comment by breedx-splk** [comment]
Unfortunately, without reworking the instrumentation I think it is still needed.  😿 

The `JdbcMaps.preparedStatements` is used to pass data from `Connection.prepareCall()` (etc) and the actual statement's `Statement.execute()`.  

When the `JdbcTracer` starts the span, it expects the `SqlStatementInfo` to have already been cached in `preparedStatements`.  Because the we start the span in `Statement.execute()`, we no longer have a SQL string to deal with (and you cannot get the string from the statement).

Do you see any other clever way out of this?

**Comment by mateuszrzeszutek** [comment]
> The JdbcMaps.preparedStatements is used to pass data from Connection.prepareCall() (etc) and the actual statement's Statement.execute().

Trrrruuuuee... I did not think of that. Hmm, I don't have any idea how we could skip this - there just has to be an association between the prepared statement and the query string. Since it cannot be avoided I'll just close this issue.
