### ISSUE TITLE
Pass Headers in HTTP requests

### ISSUE THREAD

**Issue by ankitnayan** [open-telemetry/opentelemetry-java-instrumentation#2280]
I guess HTTP requests are not supported in OTLP format. We can only use GRPC. 
Given, the above is there a way to pass headers to HTTP requests either in Jaeger, Zipkin format, or in any other way?

I can find `OTEL_EXPORTER_OTLP_HEADERS ` to set headers in OTLP but it uses only GRPC communication. Any way around?

**Comment by anuraaga** [comment]
Hi @ankitnayan - could you describe a bit what headers are you passing? Do you need to pass headers for authentication? Also is there a specific reason you can't use gRPC with OTLP? That would be our recommended method if you're using the OpenTelemetry collector, other formats may have degradation in the exported data since they use a different data format.

We currently don't have any configuration defined for the other exporters

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md

**Comment by ankitnayan** [comment]
@anuraaga I wanted to pass access_token for authentication. 
I am not very familiar with GRPC used in north-south communication. I have used NGINX in the past. Do you recommend using any GRPC compatible reverse proxy?

**Comment by anuraaga** [comment]
@ankitnayan My personal experience has generally been with direct authentication without proxies. But gRPC is just HTTP/2 in terms of how headers are handled - any HTTP/2 proxy would work for authentication. NGINX has had support for a couple of years so I think you could use it.

**Comment by trask** [comment]
Closing, but please let us know if you are still having this issue and we will re-open.
