### ISSUE TITLE
Remove HttpServerTest.testExceptionBody

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2343]
We have this sort of assertion in `HttpServerTest.test exception`

```
    if (testExceptionBody()) {
      assert response.body().string() == EXCEPTION.body
    }
```

All this does is test the behavior of the library when an exception is thrown, without any relation to OpenTelemetry or tracing. I think we can remove this assertion.

**Comment by anuraaga** [comment]
`redirectHasBody` seems to also be similar, don't think we really need it.

**Comment by iNikem** [comment]
Doesn't this test that expected exception is thrown?

**Comment by anuraaga** [comment]
Well it's basically just verifying that the exception message is copied into the response body - there is no http convention, formal or even informal I think - for such behavior. So while it might provide a double-check for some libraries, it seems to not be general enough to be worth it to me.

**Comment by laurit** [comment]
I'm also support removing it. The main issue it has is that you need to change server configuration so that error page prints the expected output. Imo there isn't much point in going through all the hassle to make this test pass. I suspect that this test isn't actually running anywhere, the only place I know of where it could pass is in `TomcatHandlerTest`, but I accidentally disable it there.
