### ISSUE TITLE
db.cassandra.table doesn't follow spec

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2476]
Currently we strip off the keyspace, but the spec says `db.cassandra.table` should be

> The name of the primary table that the operation is acting upon, including the schema name (if applicable)

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#cassandra

I think we should either keep the keyspace as part of `db.cassandra.table`, or request an update to the spec.

**Comment by FrankSpitulski** [comment]
I’d prefer an update to the spec as long as the keyspace is going to stay a tag. Including the keyspace in the table tag is redundant, increases cardinality, and makes matching a specific table name on the table tag more difficult since you’d have to match on both the keyspace and keyspaceless value.

**Comment by trask** [comment]
@FrankSpitulski would you mind submitting a spec update for this?

**Comment by trask** [comment]
This was resolved (aligning with spec) in #3066 and #3126
