### ISSUE TITLE
OpenTelemetry API instrumentation (bridge) tests are only run against latest OTel API

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3044]
And no muzzle either.

We want to run muzzle against 1.0.0+, and we want to run tests at least against 1.0.0 and latest.

**Comment by mateuszrzeszutek** [comment]
For muzzle to work we'd have to have multiple versions of `application.io...` shaded libs - the easiest way would probably be to publish `opentelemetry-api-shaded-for-instrumenting`

**Comment by trask** [comment]
Let's keep this open to track publishing of the old versions and running the tests against 1.0.0 + latestDep

**Comment by anuraaga** [comment]
Is everyone comfortable with just changing the dependency version in the `build.gradle.kts` for the opentelemetry-api-shaded-for-instrumenting project instead of checking out old tags?

This actually made my brain realize - should we move this project to the `opentelemetry-java` repo for internal consumption? This repo's versions don't necessarily sync with that one at the patch level

**Comment by trask** [comment]
> Is everyone comfortable with just changing the dependency version in the `build.gradle.kts` for the opentelemetry-api-shaded-for-instrumenting project instead of checking out old tags?

👍

> This actually made my brain realize - should we move this project to the `opentelemetry-java` repo for internal consumption? This repo's versions don't necessarily sync with that one at the patch level

oh, great thought, this totally makes sense

**Comment by trask** [comment]
Closing, the situation is much better now, can revisit later if anyone has renewed interest.
