### ISSUE TITLE
Remove version string from "final" jar

### ISSUE THREAD

**Issue by johnbley** [open-telemetry/opentelemetry-java-instrumentation#310]
Since our users have to modify startup scripts, config files, etc. to add the -javaagent:/path/to/our.jar parameter, we should be nice to them and only require them to touch that stuff once.  Instead of naming our jar "opentelemetry-auto-0.2.1.jar", it should just be "opentelemetry-auto.jar".  That way they can upgrade to a new version without changing scripts/config files/etc (or introducing secondary complexities like variable names holding the latest version name, etc.).

**Comment by tylerbenson** [comment]
This is how we've documented downloading it in Datadog:

```
wget -O dd-java-agent.jar 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=LATEST'
```

The caveat is that sometimes Maven Central is slow to update and have seen it go down for short periods of time.

**Comment by trask** [comment]
I'm warming to this idea.

It would clean up our getting started doc.

Currently we use `<version>` as a placeholder, e.g.

```
-javaagent:path/to/opentelemetry-auto-<version>-all.jar
```

Also, if we remove the version number in the Github Release attachment, then we can have a fixed "latest" download url that we can use in the getting started doc also:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-auto-all.jar

(using the "latest" download url requires not marking our releases as "pre-release", but i think that's ok since the point of marking releases as "pre-release" is so that they don't hide the latest release)
