### ISSUE TITLE
JavaExecutorInstrumentation  miss advice for 'scheduleAtFixedRat' and 'scheduleWithFixedDelay' methods

### ISSUE THREAD

**Issue by stefvic** [open-telemetry/opentelemetry-java-instrumentation#3184]
**Describe the bug**
The current `JavaExecutorInstrumentation` miss advice for `ScheduledExecutorService#scheduleAtFixedRate(..)` and `ScheduledExecutorService#scheduleWithFixedDelay(..)` which cause parent context propagation issue.

**What version are you using?**
`1.3.0-SNAPSHOT`, 935eeae

**Comment by trask** [comment]
hey @stefvic!

Can you describe your use case a bit? Are you using a higher level framework that we could instrument instead? Is manual context propagation an option?

Propagating context too broadly can lead to the context leaking unexpectedly into other operations, so we try hard to avoid that, e.g.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2436499a09ef845a9185a0cb3c5af43911d717e7/javaagent-api/src/main/java/io/opentelemetry/javaagent/instrumentation/api/concurrent/ExecutorInstrumentationUtils.java#L21-L116

**Comment by stefvic** [comment]
Hey @trask,
I don't have a specific use case. 
Actually, I'm troubleshooting another issue https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3096 and while walking through the code I observed that the current  `JavaExecutorInstrumentation` will not propagate parent context for 2 more methods `ScheduledThreadPoolExecutor`. I added test use cases in the linked PR. It makes sense to me to add those methods to auto context propagation because two methods are already covered by the current instrumentation code. 

How did I observe that?
As I mentioned before, I'm looking into context propagation issue in one of the reactor thread pool executor:
`reactor.core.scheduler.BoundedElasticScheduler$BoundedScheduledExecutorService` which extends 'ScheduledThreadPoolExecutor'. So, let's assume some of reactor API  (or other 3rd party libraries) may use internally those methods to execute delayed|perodic tasks provided by the application which may want to use OTEL tracing API inside that runnable task.

**Comment by richardstartin** [comment]
In the Datadog tracer we effectively instrument these methods automatically because we instrument subclasses of `FutureTask` - this approach has the advantage of working when the user's `Runnable` is reused (a new `ScheduledFutureTask` is created each invocation) and is insensitive to lambdas, so we never need to wrap and risk a `ClassCastException` in `ThreadPoolExecutor.beforeTask` or `ThreadPoolExecutor.afterTask`. This approach also has the nice advantage of unifying `Future`, `Callable`, and some of the `Runnable` instrumentation in a single instrumentation, which leads to much less instrumentation overhead, fewer context stores, fewer context fields which makes all `Callable`, `Future` objects smaller. and so on.

However, @trask is right that because this is so low level it does lead to context leaks - we have had to spend some time tracking down and excluding things like background chores, timeout tasks and so on, and can only exclude the ones we know about.

**Comment by stefvic** [comment]
Thank you @richardstartin @trask for detailed explanations. 

Now, I understand that those methods have been excluded in purpose and see the difference w/ actual `schedule` advice support: it is for the non-repeatable task  `ScheduledFutureTask` only.

It will be good to have some notes in the current code
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/b277fd96c575c39dd2685eb932b5ef2b1af28d46/instrumentation/executors/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/javaconcurrent/JavaExecutorInstrumentation.java#L61
that other two methods from `ScheduledThreadPoolExecutor` are excluded in purpose .
