### ISSUE TITLE
smoke-tests need retry

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3308]
I'm frequently seeing one out of the dozens of smoke tests fail in a build causing the need to retry the whole workflow. Looks like we need the retry step on these too.

**Comment by trask** [comment]
linking in related discussion: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2831#issuecomment-824039735

**Comment by laurit** [comment]
@anuraaga have you checked what causes them to fail? I looked at the last builds and only https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/938087584 fails due to smoke test, if there were others thy have probably been rerun. From the failing run one has a million stack traces for `java.lang.ClassCircularityError: java/util/concurrent/atomic/AtomicReferenceArray` which is a bug, we need to preload classes used by transformation. And the other one fails with
```
Run ./gradlew :smoke-tests:test -PsmokeTestSuite=other --no-build-cache
Downloading https://services.gradle.org/distributions/gradle-7.0.1-bin.zip

Error: Exception in thread "main" javax.net.ssl.SSLException: readHandshakeRecord
```
Perhaps @iNikem can help with this one, imo we should cache gradle wrapper as downloading it fails quite often.

**Comment by anuraaga** [comment]
@laurit I didn't check in detail, and usually just hit the retry button so the record of the failure doesn't remain, I'll try to use force push instead to keep it next time. I think I saw it twice today but retried them.

If we can fix without retry of course even better :)

**Comment by trask** [comment]
Closing, this is probably(?) outdated
