### ISSUE TITLE
Consider using spring's dependency management gradle plugin

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#3572]
Instead of implementing dependency management ourselves, do you think we could use spring's dependency management [gradle plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin)? We use that in our distro: https://github.com/signalfx/splunk-otel-java/blob/main/buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts

One advantage of that is that we'll no longer need to use `afterEvaluate` to force all configurations to extend dep management config: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts#L68-L74

I just got the following error because of that:
```
org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':testing:agent-for-testing:javaagentLibs' after it has been resolved.
```
And dependency management was completely not needed for that configuration.

**Comment by anuraaga** [comment]
I've used spring dependencies in the past and it had its own corner cases I recall, mostly related to outputted POMs. 

We don't really implement dependency management ourselves, 99% of it is Gradle with its `java-platform` and I guess we'd generally prefer something native over not.

`afterEvaluate` there was recommended by Gradle team only because those properties aren't guaranteed to have been set by a plugin at creation time

https://github.com/gradle/gradle/issues/12016#issuecomment-579177392

We could alternatively just explicitly list out the configurations to apply it to if there are issues though.

I haven't seen that error, how did you find that?

**Comment by mateuszrzeszutek** [comment]
> We could alternatively just explicitly list out the configurations to apply it to if there are issues though.

That would be fine too, I guess we could limit the configurations to "standard" ones.

> I haven't seen that error, how did you find that?

I tried to add a `javaagentLibs` configuration in one of my cleanup PRs: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3570/commits/5921a6563d0e9c5781946325d1a909e38f9d5f1c#diff-69a6919aa051eca3ff60d8611d24899a21e1c2c240119b5d9c75094764ae43c0R17-R20
That configuration would get resolved in the `shadowJar` task, which I guess was before that `afterEvaluate` ran.

**Comment by anuraaga** [comment]
Ah - I guess you should just leave out the canBeResolved flag and resolve slf4j with `versions` for this one configuration. Does that work ok?

**Comment by mateuszrzeszutek** [comment]
Hmm, let me try that

**Comment by mateuszrzeszutek** [comment]
Looks like it works, thanks!

Let's close this issue, if it doesn't break anything anymore I have no problems with our current way of managing dependencies.
