### ISSUE TITLE
Decide if overhead tests should more tightly integrate in the main project.

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#3689]
In #3627, we discussed whether or not the overhead benchmarks should be added to the project (via gradle settings) and also whether or not they should build the latest agent (vs. fetching the latest snapshot).

We should discuss this and decide on an approach together. There are pros and cons to both.

## Adding to root project

**Pros:** No additional gradle wrapper bloat. Leverage/reuse other project gradle components.
**Cons:** Zzzz. Overhead project made slower/bloated.

## Building agent
**Pros:** always testing against latest/tip. Won't fall behind.
**Cons:** slower build.

**Comment by anuraaga** [comment]
> Cons: Zzzz. Overhead project made slower/bloated.

Have you tried not importing all the modules in IntelliJ using the module selector functionality it has? Since there don't have to be actual project dependencies, just shared build scripts, I'd expect it to work pretty well for this one.

> Cons: slower build.

Since we can develop locally by setting it to test release build, is it a big problem to also support building against local agent? Assuming the above point is addressed since I think the main implication is requiring the shared build

**Comment by iNikem** [comment]
> **Pros:** No additional gradle wrapper bloat.

We don't need to have yet another wrapper jar anyway. This argument is moot.

**Comment by trask** [comment]
Closing, we can always revisit later if someone wants.
