### ISSUE TITLE
Add support to configure trace sampling probability

### ISSUE THREAD

**Issue by cmouli84** [open-telemetry/opentelemetry-java-instrumentation#374]
Right now all traces are exported by default. Adding a configuration property `ota.trace.sampling.probability` will allow configuring the sampling probability to support basic sampling use cases. 

`ota.trace.sampling.probability` can have below values

- `1 (Default)` - ALWAYS_ON sampler will be used which is the current default behavior
- `0` - ALWAYS_OFF sampler will be used
- `> 0 && < 1` - Probability sampler will be used
- `< 0 || > 1` - invalid value

**Comment by trask** [comment]
It looks like this will be resolved by https://github.com/open-telemetry/opentelemetry-java/pull/1255 (once we update to otel-java 0.5.0).

**Comment by RashmiRam** [comment]
@trask AFAIK, We still have to update the TraceConfig instance to read from env values using this https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java#L88 in https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/agent-tooling/src/main/java/io/opentelemetry/auto/tooling/TracerInstaller.java#L73 since default TraceConfig instance is used in the provider https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSharedState.java#L35 

Once we update to 0.5.0, I can raise a PR for the same. Please let me know your thoughts too.

**Comment by trask** [comment]
Hi @RashmiRam, oh yes, great point! A PR for this once we update to 0.5.0 would be super!

**Comment by RashmiRam** [comment]
@trask I see that we created a separate branch depending on otel java 0.5.0-snapshot, Would it be alright if I raised a PR for this issue against that branch?

**Comment by iNikem** [comment]
@RashmiRam Otel-java is expected to release 0.5.0 yesterday or today. Then we can merge our snapshot branch to master and master will use otel-java 0.5.0. So you can either make a PR now against our snapshot branch or wait some days and make a PR against master. Both options are totally fine :)

**Comment by iNikem** [comment]
@RashmiRam master branch now uses otel-java 0.5.0

**Comment by mnottheone** [comment]
My understanding is this has been released in 0.4.0. [Docs doesn't reflect these parameters](https://github.com/open-telemetry/opentelemetry-java-instrumentation#configuration-parameters-subject-to-change). <br>
Below should set sampler probability to 0.2 <br> 
`java -javaagent:path/to/opentelemetry-auto-all.jar 
     -Dota.exporter=zipkin
     -otel.config.sampler.probability=0.2
     -jar myapp.jar`

If yes, should we update he docs ?

**Comment by trask** [comment]
The docs should be updated correctly now as of `0.7.0`
