### ISSUE TITLE
Allow configuration of custom sampler

### ISSUE THREAD

**Issue by patsonluk** [open-telemetry/opentelemetry-java-instrumentation#387]
Similar to #374 , but also allow adding a property such as `ota.trace.sampler.jar` (similar to the `ota.exporter.jar`) so a custom sampler can be provided?

It will be helpful if one can define a sampler that sample based on certain URL pattern, for example skipping all static resources

Many thanks!

**Comment by trask** [comment]
For a common use case like ignoring certain url-patterns, it would be nice if this could be a configuration setting (instead of needing to write a custom sampler).

**Comment by agamjain2012** [comment]
This looks like a good first patch. I'm thinking of picking it up. At a high level if anyone can tell me what all would need to be done? 
I've read most of the code and my env is set up

**Comment by anuraaga** [comment]
In #427 I have come up with a nice pattern for configuring the `TracerProvider` using the API's SPI for `IdsGenerator`. However, it's very limiting that this is basically the only thing we can configure.

https://github.com/open-telemetry/opentelemetry-java/blob/c558a9651b86b6b69a61a4cc7e9148991d59c03b/sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdkProvider.java#L162

It would be great if the builder itself can accept span processors, samplers, and propagators. If there is worry about the order of operations, this could be `Supplier<SpanProcessor>` etc instead. Then there's just one entry point to configure all of these via SPI. Presumably there's some tension for propagators since those are an API concept, not SDK concept, but somehow that should be configurable with SPI if possible. Then, the initializer jar or a shaded agent can configure the SDK to whatever it needs /cc @shengxil

https://github.com/open-telemetry/opentelemetry-java/issues/1149 is a little related, but that is about manual configuration, which is also important. But I guess here we want to still have this functionality when auto configuring.

**Comment by shengxil** [comment]
+1 
AWS X-Ray tracing relies on a remote sampler to load sampling rule from the server end. It would be helpful for us to preconfigure the sampler for the OT auto instrumentor for our customer.

**Comment by anuraaga** [comment]
Do you think #561 is enough to close this since we do allow configuration of custom sampler now? Or do we have any ideas on how to do something sampler-specific as opposed to the general discussion of distros we're having in other issues?

**Comment by trask** [comment]
👍 at this point, the plan is for all code-based hooks (e.g. adding a custom sampler) to require creating your own custom "distro" of the javaagent
