### ISSUE TITLE
Remove/hide TypeTransformer.applyTransformer method

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#4220]
In order to reduce public surface that we have to support in the extension API, I propose to remove or hide `io.opentelemetry.javaagent.extension.instrumentation.TypeTransformer#applyTransformer`. I don't know any use-case that we want to publicly support that cannot be solved by `io.opentelemetry.javaagent.extension.instrumentation.TypeTransformer#applyAdviceToMethod` method.

One of the internal instrumentation uses it, `InnerClassLambdaMetafactoryInstrumentation`.  Although I understand the reasons for that, but `LambdaInstrumentationModule` uses 2 very rarely used parts of our public API that otherwise could be hidden from the publich. The second one being `io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule#getMuzzleHelperClassNames`. If we could rewrite this module to a more standard API, we could simplify public surface before declaring it stable.

/cc @laurit

**Comment by mateuszrzeszutek** [comment]
For a bit broader context: I think that `applyTransformer` was introduced as an example of how to solve https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2685

**Comment by laurit** [comment]
Firstly about `io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule#getMuzzleHelperClassNames` by removing this we make muzzle a **required** component for writing instrumentation. Are you sure it is not better to keep muzzle as an **optional** component that besides providing some safety helps by automatically finding helper classes. There is bound to be a day when a customer walks in and insists that he needs to build an extension using maven, it would be best not to make it completely impossible.
As for `InnerClassLambdaMetafactoryInstrumentation` it is possible to rewrite it using advice by having a thread local that passes context from other method to called method. `getMuzzleHelperClassNames` usage can be removed from the same instrumentation by having a dummy advice class that doesn't match anything but uses the helper class, that should be enough to have muzzle pick it up. Or could move helper to bootstrap as it is defined there anyway.
Instrumentation with just enter/exit advice is rather limited which is not necessarily a bad thing. Having advice classes written in java is nice and having muzzle that can disable instrumentation instead of breaking application when library contains an incompatible change is also nice. Sometimes advice just isn't enough, like with the `InnerClassLambdaMetafactoryInstrumentation` where you need to change the result of a method that is called in another method. Whilst it could be written by using advice it would be in a slight roundabout way. I'm sure we'll find other cases where having access to proper bytecode library comes handy. I'm actually doing a small experiment currently in our agent distro where I needed to add a field to a class, this would be impossible with just advice. I would argue that this method really doesn't add much to our api surface as our transformation api is already married with byte-buddy and this method only exposes a bit of byte-buddy which we can't get rid of without breaking everything anyway.
The way I see it our current transformation api has two problems that would be nice to solve before declaring it stable. Firstly minor changes in library can force us to need to copy paste instrumentation to another module to satisfy muzzle. It would be nice if we could have a better strategy for dealing with it.
Secondly our transformations are super slow. I believe this is because a lot of our instrumentations use matchers like `implementsInterface(named("org.eclipse.jetty.server.Handler"))` which means that for every transformed class byte-buddy has to find bytes for its super class and interfaces and check whether by any chance this interface is implemented.
There is `classLoaderOptimization` method that is supposed to keep these expensive matchers at bay but it probably doesn't help much as there is always at least one instrumentation for which `classLoaderOptimization` passes. I wouldn't be surprised if removing it wouldn't affect startup time of real applications.
I believe super hierarchy based matchers could be made to work efficiently. We could hook into `defineClass` and parse super and interface names from bytecode (this should really be quite cheap) and load super and interfaces before class is really loaded. Then during transformation we could use the actual super and interfaces of transformed class for matching. Loading super and interfaces before class is safe because these will be loaded anyway.
Though this sill wouldn't help much because there are matchers like
```
  @Override
  public ElementMatcher<TypeDescription> typeMatcher() {
    return hasSuperType(
        isAnnotatedWith(named("javax.ws.rs.Path"))
            .or(declaresMethod(isAnnotatedWith(named("javax.ws.rs.Path")))));
  }
```
which I don't know how we could make efficient. One bad matcher that needs to parse bytes of other classes pretty much ruins everything. Before declaring api stable we should make sure that we can provide an efficient implementation for it.

**Comment by iNikem** [comment]
> Firstly about `io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule#getMuzzleHelperClassNames` by removing this we make muzzle a **required** component for writing instrumentation. Are you sure it is not better to keep muzzle as an **optional** component that besides providing some safety helps by automatically finding helper classes. There is bound to be a day when a customer walks in and insists that he needs to build an extension using maven, it would be best not to make it completely impossible.

This is a very good question, I add that to the next SIG meeting agenda.

**Comment by iNikem** [comment]
> The way I see it our current transformation api has two problems that would be nice to solve before declaring it stable.

@laurit Can you please create two issues specifically for this (very valid) problems?

**Comment by mateuszrzeszutek** [comment]
> Secondly our transformations are super slow. I believe this is because a lot of our instrumentations use matchers like `implementsInterface(named("org.eclipse.jetty.server.Handler"))` which means that for every transformed class byte-buddy has to find bytes for its super class and interfaces and check whether by any chance this interface is implemented.
> There is `classLoaderOptimization` method that is supposed to keep these expensive matchers at bay but it probably doesn't help much as there is always at least one instrumentation for which `classLoaderOptimization` passes. I wouldn't be surprised if removing it wouldn't affect startup time of real applications.

Some time ago I entertained the idea of automatic generation of the `classLoaderOptimization()` method (in the runtime) -- if we wrote our own set of type matchers (both interfaces and implementations) that completely hide/wrap over the BB ones we could, somewhere in the agent internals, iterate over the whole matcher tree and collects classpath/classloader requirements from them. E.g.
```java
  @Override
  public TypeMatcher typeMatcher() {
    return implementsInterface("org.eclipse.jetty.server.Handler");
  }
```
The `TypeMatcher` class/interface could have an internal `classLoaderOptimization()` method that'd return `hasClassesNamed("org.eclipse.jetty.server.Handler")`. This would hide the optimization method from the instrumentation authors.

Of course, if we had our own type matchers implementations we could also apply other optimizations, like

> We could hook into defineClass and parse super and interface names from bytecode (this should really be quite cheap) and load super and interfaces before class is really loaded. Then during transformation we could use the actual super and interfaces of transformed class for matching.

and we could do that even after the first stable release of extension-api (since it'd be a change of implementation)

**Comment by mateuszrzeszutek** [comment]
> > Firstly about `io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule#getMuzzleHelperClassNames` by removing this we make muzzle a **required** component for writing instrumentation. Are you sure it is not better to keep muzzle as an **optional** component that besides providing some safety helps by automatically finding helper classes. There is bound to be a day when a customer walks in and insists that he needs to build an extension using maven, it would be best not to make it completely impossible.
> 
> This is a very good question, I add that to the next SIG meeting agenda.

I wonder if we could use the `HelperResourceBuilder` for that - a `.class` file is a kind of a resource after all.

**Comment by laurit** [comment]
> Some time ago I entertained the idea of automatic generation of the `classLoaderOptimization()` method (in the runtime) -- if we wrote our own set of type matchers (both interfaces and implementations) that completely hide/wrap over the BB ones we could, somewhere in the agent internals, iterate over the whole matcher tree and collects classpath/classloader requirements from them. E.g.
> 
> ```java
>   @Override
>   public TypeMatcher typeMatcher() {
>     return implementsInterface("org.eclipse.jetty.server.Handler");
>   }
> ```
> 
> The `TypeMatcher` class/interface could have an internal `classLoaderOptimization()` method that'd return `hasClassesNamed("org.eclipse.jetty.server.Handler")`. This would hide the optimization method from the instrumentation authors.
> 
`hasClassesNamed` involves resource lookup from ClassLoader which is the same thing that makes `implementsInterface` slow. It would be best if we could use it sparingly.
Another method that uses ClassLoader resource lookups is `classLoaderMatcher`. The way we use it for detecting framework versions is slightly flawed. There are applications that accidentally bundle multiple versions of the same library inside the same webapp. There are also applications where webapp with child first classloading has a different version of library than parent class. In ideal world we would base our decision on how to instrument some class only on the input bytes.

**Comment by iNikem** [comment]
I agree that this method is useful and should stay, closing this ticket. @laurit please file separate issues for your suggestions.
