### ISSUE TITLE
Remove VirtualField agent fallback to weak map

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4241]
See discussion at https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4218#discussion_r717502946

In particular, the benefit of avoiding the fallback is that it can lead to memory leaks if not careful (e.g. #441 and #3027).

One concern about removing the fallback was identified:

> there is hack that skips field injection on classes annotated with `javax.decorator.Decorator`

I think my comment was not correct:

> I wonder if the `javax.decorator.Decorator` hack is needed since #3948

because it looks like the `javax.decorator.Decorator` hack is just an ignore matcher.

@laurit just confirming that I understand your concern correctly, does the concern apply to everything in ignores matchers? and if that's the case, if we remove the fallback, wouldn't tests for any instrumentation that uses a VirtualField key that is in an ignore matcher fail?

**Comment by laurit** [comment]
I meant https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/635acd41f40f3cd24117273bf7073597c06695b0/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/context/FieldBackedProvider.java#L404 this is separate from ignores matcher. I don't think ignore matcher applies to field injection.
If we decide to remove the fallback then we have to keep in mind that there are classes that don't have the field. We add field to all subclasses of `Runnable`. `Thread` is a `Runnable`, but doesn't have the fields because it is loaded too early.

**Comment by laurit** [comment]
Field injection could also fail when `hasSuperType` matcher can't find some super types. This happens when `getResourceAsStream` of class loader that defines the class can't find bytes for some of the super types. It could be that this class loader doesn't implement `getResourceAsStream` in a sensible way or defined class has a generated super type (`ClassLoader.getResourceAsStream` won't find anything for generated classes) or in osgi it should be possible to have class hierarchies where class sees its immediate super types but not their super types.

**Comment by trask** [comment]
@laurit do you think there's anything to be done here, or should we close it?

**Comment by laurit** [comment]
@trask I think we should close this. There are classes that are loaded before field injection is set up and rely on the fallback to function properly, for example `java.util.concurrent.FutureTask`. 
To find classes that rely on fallback you can print out the key in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/865a4bbd43d192566d8234a48bdff84823bdffcc/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/field/VirtualFieldImplementationsGenerator.java#L295 and run executor tests.
