### ISSUE TITLE
'Embed extensions'  is used in multiple moudle project

### ISSUE THREAD

**Issue by chenjiazhix** [open-telemetry/opentelemetry-java-instrumentation#4701]
My library has many versions (1.1,2.0...).I want to write Embed extensions for them separatly,then build a single jar. But I see the 'demo Embed extensions' (opentelemetry-java-instrumentation\examples\extension) ,it is a single moudle project. I am poor at Gradle. How can I do to config the Gradle ?

**Comment by chenjiazhix** [comment]
@laurit  Is it a bug?

**Comment by laurit** [comment]
@chenjiazhix from your initial question I'd assume that this is not a bug but rather a question about using gradle. I'd suggest you to first start with building extensions separately. For a multi module sample project see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/distro you'll just have to list your modules in settings.gradle. To combine multiple jars into one use https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow this plugin is also used in example distro, though be warned that the `shadowJar` usage in distro is a bit convoluted because of moving classes unders `inst`. I'm sure you can find easier samples. Make sure you don't forget to use `mergeServiceFiles()` with the `shadowJar` task.
