### ISSUE TITLE
metrics attributes don't set span

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-java-instrumentation#4946]
Here I hava a requirement like this: I definded some metrcis,so I need implement AttributesExtractor to extract the Attributes that fill metrics,but the metrics Attributes I don't want to set Span. Can the agent do that?

**Comment by mateuszrzeszutek** [comment]
Hey @yangtaoran ,

We usually recommend using the [collector's processors](https://opentelemetry.io/docs/collector/configuration/#processors) to remove unneeded attributes.

If you're not using the collector, you can achieve a similar thing by creating an [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension) that contains an [`AutoConfigurationCustomizerProvider`](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizerProvider.java) SPI implementation that calls [`AutoConfigurationCustomizer#addSpanExporterCustomizer()`](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java#L55) to modify the exporter so that it does not send the unwanted attributes.

**Comment by yangtaoran** [comment]
Thanks @mateuszrzeszutek, I think use the  collector's processors is best.I close the issue.
