### ISSUE TITLE
No CPU usage metrics?

### ISSUE THREAD

**Issue by golx** [open-telemetry/opentelemetry-java-instrumentation#4986]
**Is your feature request related to a problem? Please describe.**
Yes, I'd like to monitor the CPU usage of my application. OTEL has memory pool instrumentation, so it'd be nice to have CPU usage next to it.

**Describe the solution you'd like**
See above.

**Comment by mateuszrzeszutek** [comment]
Hey @golx ,
The OpenTelemetry Collector already captures CPU metrics via the [host metrics receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver). Have you tried using it instead?

**Comment by ryanrupp** [comment]
I haven't actually enabled this but the Oshi instrumentation [appears to capture cpu time](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/oshi/library/src/main/java/io/opentelemetry/instrumentation/oshi/ProcessMetrics.java#L42) (system vs user) for the process. It also has OS level metrics but doesn't appear to capture OS level CPU usage. It also looks like it requires the Oshi jar to exist on your classpath to auto-enable.

For what it's worth, in the custom agent distribution I created, I added Java based OS/process metrics just using the JMX APIs i.e. `com.sun.management.OperatingSystemMXBean` - relies on the Sun API though because the standard API `java.lang.management.OperatingSystemMXBean` doesn't really expose enough useful data. I did this mainly for ease of installation I have some externally managed installs that do not use the collector on each machine but still wanted to be able to collect basic OS/process stats. With `com.sun.management.OperatingSystemMXBean` you can collect:

1. OS level CPU utilization
2. Java process CPU utilization
3. OS memory usage
4. OS disk/swap usage

**Comment by ryanrupp** [comment]
Re: oshi, relates to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1566 to add some documentation around how to enable

**Comment by trask** [comment]
> For what it's worth, in the custom agent distribution I created, I added Java based OS/process metrics just using the JMX APIs i.e. `com.sun.management.OperatingSystemMXBean`

@ryanrupp would you be interested in contributing this to https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics?

Our goal for oshi is that it should only be needed for things that aren't available already from the JVM.

**Comment by ryanrupp** [comment]
@trask I can look to submit a PR for this, the main limitation being the use of a `com.sun` API, but it just no-ops if under some other JVM without the API being available. I did reference the `com.sun` class statically though so I guess if there's a requirement to be able to compile with other JVM implementations that may not have this class then it could just be done reflection based (Elasticsearch uses that approach for reference).

I also did run into an obscure issue where `OperatingSystemMXBean#getSystemCpuLoad` on Windows started reporting incorrect values after ~25 days of process uptime. This ended up lining exactly with when the process uptime passed 32 bit signed int milliseconds of uptime. So seems like an overflow bug there but I couldn't find any relevant issues in OpenJDK and I didn't pursue it further (was running Java 11 for reference).

**Comment by anuraaga** [comment]
> This ended up lining exactly with when the process uptime passed 32 bit signed int milliseconds of uptime.

Interesting experiment. I skimmed through JDK code and found it truncates to double when converting from nanos to ms - I don't see any reason for this to be a Windows-specific truncation at a glance. But double should still be enough and couldn't find any spots with obvious 32-bits. Maybe just a Windows quirk. Anyways just for history / sharing:

https://github.com/openjdk/jdk/blob/jdk-11+28/src/java.management/share/classes/sun/management/VMManagementImpl.java#L185
https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.management/share/native/libmanagement/VMManagementImpl.c#L194
https://github.com/openjdk/jdk/blob/jdk-11+28/src/hotspot/share/services/management.cpp#L887
https://github.com/openjdk/jdk/blob/jdk-11+28/src/hotspot/share/services/management.cpp#L2063

https://github.com/openjdk/jdk/blob/jdk-11+28/src/hotspot/os/windows/os_windows.cpp#L715
https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter

**Comment by trask** [comment]
> @trask I can look to submit a PR for this, the main limitation being the use of a `com.sun` API, but it just no-ops if under some other JVM without the API being available. I did reference the `com.sun` class statically though so I guess if there's a requirement to be able to compile with other JVM implementations that may not have this class then it could just be done reflection based (Elasticsearch uses that approach for reference).

reflection sounds good 👍
