### ISSUE TITLE
Use "-all" for the agent with everything

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#510]
I'm warming up to the idea of using `-all` for the agent with everything (e.g. see https://github.com/open-telemetry/opentelemetry-java/pull/1323#discussion_r439708515).

If we do go this route, one question is should `-all` be a classifier, or should it be a separate artifact?

I think I've typically seen this as a separate `-all` artifact, e.g. `netty-all` and `grpc-all`, instead of as a classifier.

**Comment by iNikem** [comment]
But classifier is added to jar name. Like `no-exporters` classifier currently.

**Comment by trask** [comment]
Yeah, it's only slightly different:

`opentelemetry-auto-all-0.4.0.jar`

vs

`opentelemetry-auto-0.4.0-all.jar`

I like the classifier approach, but it does seem different than the approach other projects have taken with their `all` artifact.

**Comment by trask** [comment]
Btw, what do you think about the first question, whether to switch the default artifact from having all exporters to having no exporters, and replacing `-no-exporters` artifact with `-all` artifact?

**Comment by iNikem** [comment]
I really don't think there is a huge difference. 95% of our users will download 1 artefact with everything included. And they will do that following our instructions `curl -O https://our_url_here`. Does not matter where that url points. Maybe it is less surprising to have this under `all` classifier indeed.

Regarding separate artefact or classifier. I think we use that approach which results in simpler build scripts. And shadow plugin by default results in `-all` classifier, so I would go this way.

**Comment by anuraaga** [comment]
Small +1 to renaming to all instead of no-classifiers. As @iNikem points out the ux seems the same, a link can point to any URL without changing the text. So the main advantage is I'd generally pick a shorter word if it means the same.

For artifact vs classifier, you can only publish one pom per artifact, regardless of classifier, so projects use it to have an artifact with a pom that depends on the world and another that doesn't. For the agent, where it's about what's bundled in or not with same (no) dependencies, classifier seems idiomatic to me.

**Comment by trask** [comment]
> For artifact vs classifier, you can only publish one pom per artifact, regardless of classifier, so projects use it to have an artifact with a pom that depends on the world and another that doesn't.

great point! even more sold on classifier now 😄
