### ISSUE TITLE
Remove hibernate-4.0 version5Test?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5210]
Does anyone know what `version5Test` is for in hibernate instrumentation?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/hibernate/hibernate-4.0/javaagent/build.gradle.kts#L55

It sets the dependencies to `5.0.0` explicitly, while latest dep tests target `5.+`, and all use the same test sources. I haven't seen this sort of pattern in other instrumentation I think so wondering if there is a special reason for it, or we can delete it?

**Comment by laurit** [comment]
I added it. I don't remember exactly why I did it. Maybe it was because tests didn't initially pass on 5.0 or maybe it was just that I wanted to have an extra version where tests are run. Hibernate 4.0.0 is 10 years old. Imo testing only the first version and the latest isn't really enough when the time between these versions is so long. I do remember seeing one case where both first and latest versions passed the tests, but intermediate versions were broken. We should consider testing more versions to lessen the risk of bad surprises.

**Comment by trask** [comment]
> We should consider testing more versions to lessen the risk of bad surprises.

👍

**Comment by iNikem** [comment]
> > We should consider testing more versions to lessen the risk of bad surprises.
> 
> 👍

Should we open an issue for this and then close this specific one?

**Comment by trask** [comment]
Closing, created #5286 with (semi-)action plan
