### ISSUE TITLE
Elasticsearch picks up the body info

### ISSUE THREAD

**Issue by chenkaiyin1201** [open-telemetry/opentelemetry-java-instrumentation#5380]
ot-plugin:io.opentelemetry.elasticsearch-rest-7.0
es-sdk:Java Low Level REST Client

The elasticsearch-sdk search method is a POST request, OT don`t support obtaining search-body info. Have you considered supporting get this info.

Thanks.

**Comment by trask** [comment]
related: https://github.com/open-telemetry/oteps/pull/234

**Comment by trask** [comment]
related to #8778

I think it would make sense to focus on establishing convention and prototype for #8778 

Since elasticsearch uses an http client under the hood, it would then be possible to capture the http body on the underlying http client span after #8778 is implemented

@chenkaiyin1201 let us know if this makes sense, and we can close this issue, thx
