### ISSUE TITLE
Failed to export spans : FRAME_SIZE_ERROR: 4740180 | v1.11.0

### ISSUE THREAD

**Issue by kamaldkannan** [open-telemetry/opentelemetry-java-instrumentation#5534]
Please help. Getting this issue while exporting to jaeger or tempo.
[otel.javaagent 2022-03-09 15:53:45:913 +0000] [Ok*************] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180

Config:
-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=***** -Dotel.metrics.exporter=none -Dotel.resource.attributes=service.name=test -Dotel.javaagent.debug=false -javaagent:/app/opentelemetry-javaagent-all.jar

**Comment by kamaldkannan** [comment]
[otel.javaagent 2022-03-09 16:20:22:071 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.11.0

**Comment by laurit** [comment]
See https://github.com/grpc/grpc-java/issues/3722. You have pointed grpc exporter at an endpoint that does not speak grpc.

**Comment by ryandens** [comment]
Right now, the jaeger-thrift exporter is not included in the javaagent by default (see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/07b5d667ec30328341be294f4cdd1389793dcb58/javaagent-exporters/build.gradle.kts#L8) and the opentelemetry-java project's autoconfigure extension does not support the automatic configuration of the `jaeger-thrift exporter` (only `jaeger`, which uses gRPC).

I'm not sure if there is a strong desire to include the jaeger-thrift exporter in the javaagent or allow automatic configuration of the jaeger-thrift exporter (see https://github.com/open-telemetry/opentelemetry-java/issues/1387). 

I believe your best bet is to configure the span exporter using the [OpenTelemetry AutoConfigure SPI](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure-spi) like this:

```java
package com.example;

import io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter;
import io.opentelemetry.sdk.autoconfigure.spi.ConfigProperties;
import io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider;
import io.opentelemetry.sdk.trace.export.SpanExporter;

public final class JaegerThriftExporterProvider implements ConfigurableSpanExporterProvider {

  @Override
  public SpanExporter createExporter(ConfigProperties config) {
    String configuredEndpoint = config.getString("otel.exporter.jaeger.endpoint");
    final String endpoint = configuredEndpoint != null ? configuredEndpoint : DEFAULT_ENDPOINT;
    return JaegerThriftSpanExporter.builder().setEndpoint(endpoint).build();
  }

  @Override
  public String getName() {
    return NAME;
  }

  private static final String NAME = "jaeger-thrift";
  private static final String DEFAULT_ENDPOINT = "http://localhost:14268/api/traces";
}
```


You would then need to shade this class and the [jaeger-thrift](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-exporter-jaeger-thrift/1.12.0/jar) exporter into the javaagent JAR like you would any other OTel extension(example of an extension here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/build.gradle)


Perhaps a single artifact that accomplishes this would be a good candidate for something to be included in the [open-telemetry/opentelemetry-java-contrib/](https://github.com/open-telemetry/opentelemetry-java-contrib/) repo

**Comment by Curlybraces3** [comment]
Hi @laurit is the above solution worked? I am facing similar issue in open elementary right now.

**Comment by trask** [comment]
@Curlybraces3 it would be best to open a new issue and explain your full details, thx

**Comment by amardeep2006** [comment]
Did face the exact same error recently and root cause for me was that our telemetry collector had only http protocol enabled on 4318 port and no grpc on 4317. Sharing my solution since this link is pretty high in search engine results.
I am using OTLP collector with otlp protocol and faced this error when tried to send trace date on grpc protocol on port 4318.
Solution : 
Set the OTEL_EXPORTER_OTLP_TRACES_PROTOCOL to http/protobuf . 
If you want to send data over grpc then make sure you have 4318 port and grpc collection enabled on your collector. 
Reference : https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#protocol-configuration

Here is the error i got.

{"class": "ThrottlingLogger","log-level": "SEVERE","log-message": "Failed to export spans. The request could not be executed. Error message: FRAME_SIZE_ERROR: 4740180","log-name": "io.opentelemetry.exporter.internal.grpc.GrpcExporter","log-time-local": "2025-05-17T10:57:46.229Z","log-time-utc": "2025-05-17T10:57:46.229Z","method": "doLog"}
10:58:46.233 ERROR [ThrottlingLogger.doLog] - Failed to export spans. The request could not be executed. Error message: FRAME_SIZE_ERROR: 4740180
java.io.IOException: FRAME_SIZE_ERROR: 4740180
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:107)
	at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:73)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
