### ISSUE TITLE
auto-instrumentation for Java Spring Kafka Streams - is NOT generating the Jaeger Deep Dependency graph with Producer and Cosnumer

### ISSUE THREAD

**Issue by dharmaplay** [open-telemetry/opentelemetry-java-instrumentation#5681]
Hi,
I have written 1 Producer and 1 Consumer using Spring Kafka streams/Cloud streams and able to see the traces in JaegerUI but when I click on the Deep Dependency graph its not showing the graph like

Producer --> Kafka TopicName --> Consumer.

Is it possible to generate Information above like Producer ->TopicName -> Consumer informations like traces and metrics?

Thanks
Dharma

**Comment by chalin** [comment]
You should direct your question to a more appropriate forum. For example, see the links to **discussions** or **mailing lists** under the [Community > Communication](https://github.com/open-telemetry/community#communication).

(Generally, you should also avoid cross-posting questions simultaneously, as you did on the OTel website repo: https://github.com/open-telemetry/opentelemetry.io/issues/1231. Otherwise, it feels like spam.)

**Comment by mateuszrzeszutek** [comment]
Hey @dharmaplay ,
I'm not sure how Jaeger deep dependencies work, can you post some example trace(s) that your system produces (gathered using e.g. logging exporter)? Or a repo containing the repro scenario for your issue?

**Comment by chalin** [comment]
(Thanks for the followup @mateuszrzeszutek. If you welcome questions like these to this repo as issues, let me know so that I can adjust my responses.)

**Comment by anuraaga** [comment]
Thanks @chalin - we welcome questions on discussions, issues, or Slack. Many questions end up in the wrong repo, channel etc reinforcing the cross-signal / language nature of OTel. Cross posting is less ideal but I think we need to be receptive and provide pointers on where to go without assuming the user did something wrong. OTel has no values, guidelines, SLAs on providing a good user experience so things will often not go as planned.

**Comment by trask** [comment]
hi @dharmaplay, what version of the javaagent are you using?

if you are not using 1.12.0+, try updating to the latest version, because disconnected kafka traces have been an issue for users prior to that version, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5385 for details

**Comment by trask** [comment]
Closing, but please let us know if you are still having issues after updating to the latest version and we will re-open.
