### ISSUE TITLE
Export jaeger-thrift over UDP

### ISSUE THREAD

**Issue by noahseger** [open-telemetry/opentelemetry-java-instrumentation#5821]
**Is your feature request related to a problem? Please describe.**

After the discussion in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1973, `jaeger-thrift` exporter support was dropped. However, in Jaeger Agent deployments, Agents are designed to only accept [thrift over UDP](https://www.jaegertracing.io/docs/1.21/apis/#thrift-over-udp-stable). This means that users need to write custom exporters to get traces into Jaeger, or trade off the backpressure provided by the agent-based deployment approach.

**Describe the solution you'd like**

Support the UDP-based Jaeger strategy as a first-class exporter.

**Describe alternatives you've considered**

If it is not a priority for the team, consider documenting that UDP exporting is not supported.

**Additional context**

Latest documentation of stable protocols https://www.jaegertracing.io/docs/1.33/apis/.

I also found this issue in the PHP library so it may be helpful for them to be able to follow a backlink from there to any discussion here https://github.com/open-telemetry/opentelemetry-php/issues/296.

**Comment by anuraaga** [comment]
We would probably need to rewrite the thrift exporter to remove dependencies on the Thrift library and autogenerated code, similar to what we did for gRPC / protobuf, to include the exporter by default in the javaagent. Is this something you would be able to help with?

Otherwise, perhaps we could publish a packaged extension jar to be able to provide on the command line more easily though as a middle ground. 

For context, I suppose that in general we hope that users can switch from the jaeger agent to the opentelemetry collector with its jaeger exporter - is this something you looked into?

**Comment by mateuszrzeszutek** [comment]
[Jaeger exporters have been deprecated](https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/#jaeger-exporter); which means we won't be adding any new Jaeger export options.
