### ISSUE TITLE
Don't require updating branch to master when merging

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#600]
I find it to take a lot of time to have to update the branch before merging since the tests take a while. The downside of not doing this is on occasion, there will be a master build breakage due to getting out of sync in a way it breaks without causing a merge conflict. In my experience this has been rare enough that there would probably be a net productivity boost by reacting to a master build break instead of always updating a PR (possibly multiple times if others get merged in between).

**Comment by iNikem** [comment]
It may be a good idea, but it requires somebody to monitor master branch builds a reacting to their breaking. Could you suggest a process about that as well?

**Comment by anuraaga** [comment]
I don't know if there's much more process than reviewers in the repo getting CircleCI notifications for failure and checking when they notice. Worst case is next time someone sends a PR they'll realize anyways. It's not the best process, but it's based on the premise that it's pretty rare, I think out of a few active repos, I've seen it just twice or so in a few years. Any anecdotal sense on how often a build goes from green -> red when hitting the update button here? If anyone's seen that happen here, then that'll be good info.

**Comment by trask** [comment]
Good idea.

I will go ahead and make this change, in particular because it will help reduce CircleCI cost (which hit $1100 in June).

I just set up CircleCI notifications so I should get email on any build failure, and will monitor. I agree (non-sporadic) build failures on master should be rare. And this will keep us on top of the sporadic failures on master, which I've currently been ignoring.

And it looks like once we move to Slack, we can set up Slack notifications too.

**Comment by trask** [comment]
Done, let's see how it goes.
