### ISSUE TITLE
OTEL_RESOURCE_ATTRIBUTES are added to the process instead of the tag in jaeger

### ISSUE THREAD

**Issue by tuhao1020** [open-telemetry/opentelemetry-java-instrumentation#6000]
I have two spring boot applications: otel-client and otel-server, using otel-java-instrumentation for trace data collection, setting the following environment variables.
```
OTEL_TRACES_EXPORTER=jaeger,logging
OTEL_EXPORTER_JAEGER_ENDPOINT=http://localhost:14250
OTEL_METRICS_EXPORTER=none
OTEL_RESOURCE_ATTRIBUTES=service.name=otel-client,key1=value1
```
Expect the tag of the span queried in the jaeger ui to contain the above OTEL_RESOURCE_ATTRIBUTES, but these attributes are placed in the process.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/26807520/167607799-f36d2dc0-47e8-48de-a45d-c46d3dd2c54f.png">

**Comment by anuraaga** [comment]
Hi @tuhao1020 - the OTel resource corresponds to the Jaeger process, it is generally "the app". Is there a reason you want them to be on the span instead?

**Comment by tuhao1020** [comment]
Because the front-end depends on the attributes in the tag, is there any other way to transfer the attributes to the tag?

**Comment by tuhao1020** [comment]
If I set OTEL_TRACES_EXPORTER to zipkin as below, then the `key1` set in OTEL_RESOURCE_ATTRIBUTES does not exist in either tag or process

```
OTEL_TRACES_EXPORTER=zipkin,logging
OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://localhost:9411/api/v2/spans
OTEL_METRICS_EXPORTER=none
OTEL_RESOURCE_ATTRIBUTES=service.name=otel-client,key1=value1
```

<img width="1924" alt="image" src="https://user-images.githubusercontent.com/26807520/167684094-1a5cd19b-36fe-485a-818c-588179579428.png">

**Comment by anuraaga** [comment]
Zipkin exporter unfortunately does not have specification for mapping resource to tags

https://github.com/open-telemetry/opentelemetry-specification/blob/f124b21de091f3d668e4ce11b954ec17e3da231f/specification/trace/sdk_exporters/zipkin.md

For Jaeger, if it's possible it would be best if the frontend you are using could be updated to support process as well - it is the precise mapping for OTel resource attributes. 

Otherwise I think you would need a javaagent extension with a `SpanProcessor` to copy the attributes into the tags

https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension
https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java
