### ISSUE TITLE
Use sampling for trace but generate metrics always

### ISSUE THREAD

**Issue by alvinhom** [open-telemetry/opentelemetry-java-instrumentation#6012]
We are planning to use the opentelemetry java instrumentation for both traces and metrics.  For traces, we want to control the amount of traces using sampling.  However, for metrics, we want to make sure that metrics are always collected even if traces are not sampled.  So, I am not sure the current behavior if sampling is set to say 0.1 ratio, will the metrics still be collected all the time.

If this is already supported, can you please describe how to configure this.  Thanks.

**Comment by breedx-splk** [comment]
Disclaimer: I'm not a _deep_ otel metrics expert.

Traces and metrics are separate concerns. Exemplars aside, the standard sampling of traces should not impact metrics measurement collection or export, which is probably what nearly everyone always wants. 

This can, in some circumstances though, lead to confusion if you're looking at a backend and see 1 single sampled span in a time period, and if the duration of that span doesn't match a similar metric around response latency or request count or whatever, it can make folks wonder why the numbers don't match.

**Comment by alvinhom** [comment]
Ok, so the default behavior is that sampling should only affect traces, but not metrics.  I have to test this and see if this is the case.  My doubt is from reading the code from the various plugins where there is always a check for sampling before any of the trace or metric processing is evaluated.  But it would be great if this is the default behavior.

**Comment by anuraaga** [comment]
The `shouldStart` method we call in instrumentation is to handle span suppression, but doesn't do a sampling decision. This is primarily to prevent duplication of spans, e.g. having two HTTP client spans. So it often is probably good that it prevents duplicate metrics - however I'm not sure if this is always the correct behavior and that perhaps sometimes we would want metrics to be created even when the span is suppressed by the dedupe logic.

On the flip side, when span suppression is disabled, we may export duplicate client spans expecting a trace UI to handle this relatively well while it's still not appropriate to export duplicate metrics. And we may even need to keep in mind the possibility, while not really happening in practice, of the same meter itself producing duplicate metrics, in which case the actual time series could have data from different code layers. 

It's good this issue was brought up since I don't know if we've dove deep into the possible scenarios here yet, and especially the possible issues when span suppression is disabled.

**Comment by trask** [comment]
I think the `semconv` and `span-kind` suppression strategies work well for metrics, or at least produce what I would expect, where it will capture (accurate) metrics corresponding to the spans that you are choosing to capture.

I think this discussion points out a danger of the `none` suppression strategy, which can lead to inaccurate (double-counted) metrics.

Maybe we need to the enhance the `none` suppression strategy to suppress duplicate metrics (while still producing "duplicate" spans)?

**Comment by mateuszrzeszutek** [comment]
> Maybe we need to the enhance the `none` suppression strategy to suppress duplicate metrics (while still producing "duplicate" spans)?

The captured metrics should have different instrumentation names; some of the exporters (prometheus) completely ignore these though...
