### ISSUE TITLE
What to do about instrumentation-specific span attributes?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#602]
We currently capture lots of instrumentation-specific span attributes that are not defined by semantic conventions.

Questions:
* Should we only capture span attributes that are defined by semantic conventions?
* Should we propose instrumentation-specific span attributes (e.g. for `aws-sdk`, `elasticsearch`, etc) in an attempt to have consistency for these across languages?
* Is there naming convention we should follow for instrumentation-specific span attributes (e.g. standard prefixing like `elasticsearch.*`)?

**Comment by anuraaga** [comment]
I think the reality is we'll need instrumentation-specific attributes to capture instrumentation domain-specific issues that are important for observability. Prefixing seems like a good idea (e.g., agree that the kafka instrumentation should do `kafka.tombstone` instead of just `tombstone`. Having these spec'd would be even nicer to allow them to be consistent across languages, I've already seen the x-ray instrumentation for AWS SDK have different naming strategies which results in pain like this

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/awsxrayexporter/translator/aws.go#L30

**Comment by iNikem** [comment]
Below is my understanding of the ideal world:

* All attributes have a clear use-case explaining their existence
* All attributes are defined in semantic convention
* All attributes are documented

While point 2 from above is harder to achieve, point 1 and 3 are more under our control. So in order to bring new attribute in we have to understand the use-case and then document it.

**Comment by anuraaga** [comment]
Definitely +1 to all attributes are documented, it's a clear bar to set and will naturally lend to point 1 and maybe point 2 depending on the attribute.

**Comment by anuraaga** [comment]
Filed spec issue https://github.com/open-telemetry/opentelemetry-specification/issues/968

**Comment by iNikem** [comment]
@anuraaga I think we can close this issue, right? This discussion is concluded and we seem to have an answer from Spec.

**Comment by trask** [comment]
I think worth adding something to `docs/` since this will probably be a common question we get about adding new span attributes (assigning to myself)

**Comment by iNikem** [comment]
#1874 and open-telemetry/opentelemetry-specification#968 concludes this discussion.
