### ISSUE TITLE
Verify actual status instead of just errored

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#608]
OTel spans have a status with different codes but many of our tests only test success vs error. We should migrate to asserting on the status instead.

**Comment by trask** [comment]
Before anyone picks up this issue, it sounds span status may be going away https://github.com/open-telemetry/oteps/pull/123#issuecomment-656910549

**Comment by breedx-splk** [comment]
There was a LOT of discussion around the removal of `Span.Status` but according to [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/706#issuecomment-664457764) it looks like there was a decision to remove it, but then according to the [actual span spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-status) today (which is frozen), spans definitely still have a status.

Since this issue has been around for a while, maybe we can tweak it to help foster contribution.  How about splitting this into smaller, more targeted issues?  There are a LOT of tests, and a LOT of usages of `SpanAssert.errored()`.  

Suggest picking our top/favorite <N> instrumentations that could benefit from status checking and put those in a new issue or calling them out by name here with more detail (eg. what status is expected and if semantic conventions are also to be verified).
