### ISSUE TITLE
a classloder problem

### ISSUE THREAD

**Issue by XiaoWeiKIN** [open-telemetry/opentelemetry-java-instrumentation#6257]
hi,  I know that `OpenTelemetrySdk` is loaded in `installOpenTelemetrySdk` using `bootstrap` classLoader and saved in `GlobalOpenTelemetry`. 

```
 GlobalOpenTelemetry.set(openTelemetrySdk);

```

than get OpenTelemetry instance  via `GlobalOpenTelemetry ` in the advice logic.

```
GlobalOpenTelemetry.get()
```
now I save a custom SDK using frameworkHolder.set (sdk) in the same way.
```
@AutoService(AgentListener.class)
public class LsfGRpcInstaller implements AgentListener {
  @Override
  public void beforeAgent(
      Config config, AutoConfiguredOpenTelemetrySdk autoConfiguredOpenTelemetrySdk) {
    GRpcChannel grpcChannel =
        GRpcChannel.builder()
            .setEndpoint("http://localhost:50051")
            .setTimeout(Duration.ofSeconds(10))
            .build();


    ServiceFrameworkSdk sdk = ServiceFrameworkSdk.builder(grpcChannel)
            .registerGRpcReporter(
                    GRpcServiceName.INSTANCE_METADATA.getName(),
                    (name, channel) ->
                            DefaultGrpcReporter.builder(
                                            name, MarshalerInstanceMetadataGrpc::newFutureStub, channel)
                                    .build())
            .registerGRpcDuplexer(
                    GRpcServiceName.LOG_LEVEL.getName(),
                    (name, chanel) ->
                            DefaultGRpcDuplexer.builder(name, BidirectionalLogLevelGrpc::newStub, chanel)
                                    .build())
            .build();

    FrameworkHolder.set(sdk);
  }
}
```
The ServiceFrameworkSdk is loaded through the AgentClassLoader, and the `FrameworkHolder` is loaded through the BootstrapClassLoader.

but when I get the ServiceFramework in the advice logic, the `FrameworkHolder `is loaded by the AppClassLoader, that's why?

```
FrameworkHolder.get();

```

![image](https://user-images.githubusercontent.com/20626345/177073162-1cf0a482-665e-4b7f-b404-1f8648a22088.png)

**Comment by mateuszrzeszutek** [comment]
Hi @XiaoWeiKIN ,
There might be many reasons why your custom `FrameworkHolder` gets loaded by the app classloader.
* Are you building a javaagent extension? Or a distro? If you want to add classes to the bootstrap CL, you'll need to create a distro, make sure that the jar is built properly (i.e. classes that are supposed to be loaded by the bootstrap CL are placed in the jar "normally"; unlike the agent CL classes), and then register the packages using the [`BootstrapPackagesConfigurer`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/bootstrap/BootstrapPackagesConfigurer.java).
* Does the instrumented app bring its own copy of `FrameworkHolder`? If so, that copy it's probably possible that the application's `FrameworkHolder` gets loaded before the agent one. In this project, we're shading the whole OpenTelemetry API so that it does not collide with the OpenTelemetry API that might be used in the instrumented application -- and then we have a separate bridge instrumentation that makes the connection between the two. It's complicated, but that helps us avoid this issue.

**Comment by XiaoWeiKIN** [comment]
This is the structure of the JAR：
![image](https://user-images.githubusercontent.com/20626345/177123717-840acdda-c72f-4e8c-a00a-3efa7aa3da94.png)

**Comment by XiaoWeiKIN** [comment]
This is a big headache

**Comment by mateuszrzeszutek** [comment]
Are you able to post a repro scenario? E.g. a super-minified version of your distro.
Unfortunately your issue touches so many different parts of the agent that it's pretty hard to find out the cause just from the description.

**Comment by XiaoWeiKIN** [comment]
@mateuszrzeszutek I'll try

**Comment by XiaoWeiKIN** [comment]
@mateuszrzeszutek I think I can provide the constructed JAR to you, and I can send it to your email if possible.

**Comment by trask** [comment]
@XiaoWeiKIN it would be ideal if you can create a personal repository with the repro with instructions how we can build/run/reproduce the issue.

**Comment by mateuszrzeszutek** [comment]
@XiaoWeiKIN I don't think I would be allowed to help you with proprietary code; please create a public repo with reproduction scenario if it's possible.

**Comment by XiaoWeiKIN** [comment]
ok
