### ISSUE TITLE
Kafka Streams agent instrumentation missing `receive` span

### ISSUE THREAD

**Issue by ppatierno** [open-telemetry/opentelemetry-java-instrumentation#6443]
I have a simple Kafka Streams API based application doing just the following processing:

```java
builder.stream(this.topicIn, Consumed.with(Serdes.String(), Serdes.String()))
                .mapValues(s -> s.toUpperCase())
                .to(this.topicOut);
```

When using the Java agent to instrument it, when I send just one message to the input topic, what I get from a tracing point of view are two spans: a `process` and `send` (which is the child).
Referring to the current messaging semantics [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#operation-names) I would have expected to have three spans: `receive` -> `process` -> `send` (each as a child of the previous one).
My expectation is based on the fact that a Kafka Streams application actually receives, processes and sends messages.
Is the receive missing on purpose? Isn't it a bug?

**Comment by laurit** [comment]
We have a similar test https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/kafka/kafka-streams-0.11/javaagent/src/test/groovy/KafkaStreamsDefaultTest.groovy that produces `receive` span. Could you provide a minimal sample app that reproduces this issue or modify the existing test case.

**Comment by ppatierno** [comment]
Interesting my application it's still fairly simple as well as your test but it doesn't produce a `receive` span :-(

https://github.com/ppatierno/kafka-opentelemetry/blob/main/kafka-common/src/main/java/io/ppatierno/kafka/opentelemetry/BaseStreams.java#L36

**Comment by laurit** [comment]
See https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#capturing-consumer-message-receive-telemetry-in-messaging-instrumentations Try adding `-Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=true` this should make the instrumentation generate the receive span.

**Comment by ppatierno** [comment]
@laurit thanks, it worked! But now I have a couple of question ...

1. why tracing the receive is something "optional" and disabled by default so that you need that property to be set?
2. why the `process` span has now two links to the `receive`: a CHILD_OF and FOLLOW_FROM. I would expect only the FOLLOW_FROM.

Following the two references I see:
```json
"references": [
                        {
                            "refType": "FOLLOWS_FROM",
                            "traceID": "df5c997a34fc22e61592c0ce3d13cfa0",
                            "spanID": "67b9e44adbb5ed34"
                        },
                        {
                            "refType": "CHILD_OF",
                            "traceID": "df5c997a34fc22e61592c0ce3d13cfa0",
                            "spanID": "67b9e44adbb5ed34"
                        }
                    ]
```

**Comment by mateuszrzeszutek** [comment]
> 1. why tracing the receive is something "optional" and disabled by default so that you need that property to be set?

Most of our users found it to be extremely confusing, because it resulted in 2 separate traces for producer and consumer sides, just linked together by a span link. We've decided to make that an optional behavior for now -- I guess we'll need to revisit this (and everything connected to the messaging instrumentations really) once the messaging semantic conventions get closer to stability.

> 2\. why the `process` span has now two links to the `receive`: a CHILD_OF and FOLLOW_FROM. I would expect only the FOLLOW_FROM.

Usually, the producer span would be extracted from the incoming message and added as a `FOLLOWS_FROM` span link; in case there's no span context attached to the message, the span link extractor just gets the parent span from the current context - which is the receive span. I think this is a somewhat minor bug, we should fix that.

**Comment by ppatierno** [comment]
> Most of our users found it to be extremely confusing, because it resulted in 2 separate traces for producer and consumer sides, just linked together by a span link. We've decided to make that an optional behavior for now -- I guess we'll need to revisit this (and everything connected to the messaging instrumentations really) once the messaging semantic conventions get closer to stability.

I don't get you, because when it's enabled I don't see 2 separate traces but just one with all the three spans: `receive` -> `process` -> `send` which makes kind of sense for a streams application right now.
Anyway I agree it's something to revisit later.

> I think this is a somewhat minor bug, we should fix that.

Do you prefer a different issue to track this?

**Comment by mateuszrzeszutek** [comment]
> I don't get you, because when it's enabled I don't see 2 separate traces but just one with all the three spans: `receive` -> `process` -> `send` which makes kind of sense for a streams application right now.

The broken trace appears between `send` and `receive`/`process`:
* in the usual scenario, with the flag turned off, there is no `receive` span and the parent of the `process` span is the `send` span;
* but when you turn it on, the producer trace ends on `send` - and the consumer starts its own trace with the `receive` span; `process` is a child of `receive` and it contains a link to the `send` trace/span.

> Do you prefer a different issue to track this?

Yes, if you could 👍

**Comment by ppatierno** [comment]
> but when you turn it on, the producer trace ends on send - and the consumer starts its own trace with the receive span; process is a child of receive and it contains a link to the send trace/span.

This is what I cannot see. I see all of them as part of the same trace.

![image](https://user-images.githubusercontent.com/5842311/184902839-250836c6-7569-4279-8ab9-44602b4d64f0.png)

Also the JSON here https://pastebin.com/JvV7gJi4
You can see all of them are in the same `76ebc3cf0a42d497f7200d883668ad4d` trace.

> Yes, if you could 

I will do!

**Comment by mateuszrzeszutek** [comment]
> You can see all of them are in the same `76ebc3cf0a42d497f7200d883668ad4d` trace.

Yeah, that's because your trace starts with `receive` and is coming from a single application. If you had 2 (or more) apps, and wanted to preserve the context when between them, you'd get 2 traces with the flag turned off.
I was talking about a different ordering of spans: `send` -> `receive` -> `process`

**Comment by ppatierno** [comment]
> If you had 2 (or more) apps, and wanted to preserve the context when between them, you'd get 2 traces with the flag turned off.

Ok. So taking Kafka Streams applications out, I tried again with two applications: producer and consumer (using the agent).

With `-Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=false` (so the default, flag turned off), I get one trace with `send` -> `process` (which is CHILD_OF `send`).

With `-Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=true`, I get two different traces:
* one with just `send`
* one with `receive` -> `process` (CHILD OF `receive`, FOLLOWS_FROM `send`)

Two things ...
You said "you'd get 2 traces with the flag turned off." .... while I see the opposite.
And `receive` should FOLLOWS_FROM `send` not the `process` imho.

**Comment by mateuszrzeszutek** [comment]
> You said "you'd get 2 traces with the flag turned off." .... while I see the opposite.

Oops, sorry for the confusion, that was a mistake on my part - I meant the reverse.

> With `-Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=false` (so the default, flag turned off), I get one trace with `send` -> `process` (which is CHILD_OF `send`).
> 
> With `-Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=true`, I get two different traces:
> 
> * one with just `send`
> * one with `receive` -> `process` (CHILD OF `receive`, FOLLOWS_FROM `send`)

That is all correct behavior according to the spec. The two-trace split that happens when you set `otel.instrumentation.messaging.experimental.receive-telemetry.enabled` to `true` is what was confusing for most of our users.

> And `receive` should FOLLOWS_FROM `send` not the `process` imho.

This behavior reflects the current spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving
Keep in mind that the messaging spec is being worked on right now, so this might change in the future - we will change this to whatever the spec recommends once it's ready.

**Comment by ppatierno** [comment]
> The two-trace split that happens when you set otel.instrumentation.messaging.experimental.receive-telemetry.enabled to true is what was confusing for most of our users.

While it's actually the right thing tbh. Producing and consuming should have two different traces but using links to reference from one to the other.

> This behavior reflects the current spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving
Keep in mind that the messaging spec is being worked on right now, so this might change in the future - we will change this to whatever the spec recommends once it's ready.

Yeah I know.

**Comment by mateuszrzeszutek** [comment]
> While it's actually the right thing tbh. Producing and consuming should have two different traces but using links to reference from one to the other.

I actually agree with you, that's why I introduced the receive span in the first place 😂 
Still, since the current messaging is kinda vague about this, and most of the telemetry vendors don't implement span links correctly, and users kept complaining about it, we've decided to turn this feature off by default. You can still turn it on, you just need to pass a configuration option.

**Comment by ppatierno** [comment]
Ok thanks, at least we are on the same page now :-D. Going to close this one!
