### ISSUE TITLE
HTTP Client Span Names

### ISSUE THREAD

**Issue by knutwannheden** [open-telemetry/opentelemetry-java-instrumentation#6526]
### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2606

<div type='discussions-op-text'>

<sup>Originally posted by **jamal** March 19, 2021</sup>
Hi all! I wanted to try to start a quick conversation around the HTTP client span names provided by most instrumentations today. I know that we need to strike a balance between something that is specific enough, but provides low cardinality, and is not taxing performance. But, most instrumentations today seem to just be providing `HTTP {method}` as the span name.

I was wondering if it would make sense to include some additional information, such as the peer name, by default. I feel that this would at least allow for separation by external service which would provide far more valuable information. I noticed that in the base `HttpClientTracer` we are already using the `URI` from the implementation to set `net.peer.name`. Would there be any reason to not use this to generate a more unique span name, such as `HTTP {method} {hostname}`?

Thanks!</div>

As discussed in the linked discussion, I also think that it would make sense if the client span names were to include a more information regarding the called endpoint, such as the target hostname or possibly the HTTP route. Some HTTP clients like MicroProfile Rest Client (as e.g. used by Quarkus) would be able to produce low-cardinality names like `/get/{id}`, which I think would be very useful to have as part of the span name.

**Comment by mateuszrzeszutek** [comment]
Hey @knutwannheden ,

About the quoted post: please take a look at https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2606#discussioncomment-569357 -- we're naming span according to the OTel semantic conventions specification, and we cannot possibly change anything here unless we get a blessing from the spec.

> Some HTTP clients like MicroProfile Rest Client (as e.g. used by Quarkus) would be able to produce low-cardinality names like `/get/{id}`, which I think would be very useful to have as part of the span name.

I 100% agree with that, it would be much better than using `HTTP GET` -- that's why we're using routes for the span names in the HTTP server instrumentations.
The problem is, very few HTTP clients have the concept of a route/template. In fact, I think that none of the HTTP clients that we instrument in this repository make use of that concept.

**Comment by knutwannheden** [comment]
@mateuszrzeszutek I see. Given that the specification uses the wording _SHOULD_ and _such as_ when providing the example, I was assuming this was a recommendation, and would give some leeway on how to implement it (e.g. use a route in the name, if available):
> HTTP client spans SHOULD be using conservative, low cardinality names formed from the available parameters of an HTTP request, such as "`HTTP {METHOD_NAME}`".

I suppose that I would instead have to file an enhancement request against Quarkus, if I want to be able to supply a custom `SpanNameExtractor`. Although the `HttpClientAttributesGetter` would then still require a `route()` method to allow extracting the route from a request.

**Comment by mateuszrzeszutek** [comment]
If you're implementing a custom `SpanNameExtractor` you can use the library types (e.g. `HttpRequest` or something) directly, without the need for a getter. The getter interfaces are used in this project to abstract away all the differences between various libraries; so that we can use the same `AttributeExtractor` implementation across all HTTP clients.

Having the route available in the HTTP client is extremely uncommon scenario, which is why we'll probably not be adding the `route()` method to the `HttpClientAttributesGetter` -- but that shouldn't stop you from getting it directly from the Quarkus HTTP request type though.

**Comment by knutwannheden** [comment]
Thanks for the explanation!

With the rise of MicroProfile frameworks (Quarkus, Micronaut, Helidon, etc.) there could soon be more applications, where the client request can provide a route. But feel free to repurpose or close this issue.

**Comment by bherbst** [comment]
How would you actually go about attaching a custom `SpanNameExtractor` to the existing instrumentors? The instrumentors I've looked at in this repo (I mostly care about OkHttp but have looked at others to see how they handle span naming) all build an `HttpSpanNameExtractor` internally with no hooks available for clients to provide their own extractor.

That's what I think is missing right now - public APIs on types such as `OkHttpTelemetryBuilder` to set a different `SpanNameExtractor`.

Otherwise we are stuck forking or re-implementing large chunks of the instrumentation library to support custom span names, which is what I'm currently doing.

**Comment by trask** [comment]
@bherbst would it work for you to create a SpanProcessor and update the span name on start?

**Comment by bherbst** [comment]
Ahhhh, I missed that a `SpanProcessor` can update the name! That definitely works, thanks!
