### ISSUE TITLE
Advice on using with Tomcat

### ISSUE THREAD

**Issue by zackman0010** [open-telemetry/opentelemetry-java-instrumentation#6682]
We're attempting to set up our monitoring infrastructure using OpenTelemetry to pull traces from our Tomcat services. We have multiple services (usually between 4 and 8) running per Tomcat instance. When the agent JAR is attached to the instance, it shows all traces as coming from the Tomcat instance. Unfortunately, we need to be able to get these traces at the service layer. Is there a way to configure the agent to use the service instead of the Tomcat for service.name, whether through configuration or code?

**Comment by mateuszrzeszutek** [comment]
Hey @zackman0010 ,
Unfortunately, currently there is no way to differentiate between different services deployed on a single application server instance; the javaagent attaches to the Java process and it treats it as a one application.
You could achieve that with manual instrumentation and setting up the OpenTelemetry SDK separately for each app, but that's a lot of effort, and requires lots of changes in the applications.

**Comment by zackman0010** [comment]
Hmm.. Is service name immutable on the trace, or could we update it using a processor in an extension?

**Comment by mateuszrzeszutek** [comment]
Hmm, I suppose you could [wrap the `SpanExporter`](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java#L133) and modify the `SpanData` it receives (well, return a new one, cause `SpanData`'s immutable) so that it gets different resources. This should work for the OTLP exporter if you're using it, it might not work that well for other exporters (Zipkin).
