### ISSUE TITLE
Can we exclude url like health check in opentelemetry for java if yes can you please provide an example

### ISSUE THREAD

**Issue by Montyroi** [open-telemetry/opentelemetry-java-instrumentation#6707]
I am trying opentelemetry in spring boot project, its collecting actuator health traces, how to exclude it in environment variables

**Comment by mateuszrzeszutek** [comment]
Hey @Montyroi ,
This feature is tracked in issue #1060, I'll close this one as a duplicate.
As I mentioned in [my last post](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060#issuecomment-1255031021) there, it's not implemented yet in the agent, but you can create a javaagent extension that filters out these spans.

**Comment by shanmukh116** [comment]
Hello , how to exclude healthcheck url from tracing in java opentelemetry?

**Comment by jaydeluca** [comment]
@shanmukh116 you have a much better chance of getting assistance if you open a new issue/discussion rather than commenting one one thats been closed for 3 years.

With that being said, here are some resources you can take a look at:

* https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/javaagent-declarative-configuration
* https://opentelemetry.io/blog/2025/declarative-config/#health-check-exclusion
