### ISSUE TITLE
Use AutoValue for value classes

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#676]
In particular, when we removed Lombok, we replaced Lombok `@Data` classes with hand-written classes. In that PR it was discussed that it would be nice to replace these hand-written classes with AutoValue or Immutables-generated classes. Since the opentelemetry-java project uses AutoValue, it probably makes sense for us to use that as well (even though [I'm personally a big fan of Immutables](https://github.com/immutables/immutables/pulls?q=is%3Apr+author%3Atrask+is%3Aclosed)).

**Comment by iNikem** [comment]
In both cases: what is the experience without IDE support? And how do IDEs support them?

**Comment by anuraaga** [comment]
> what is the experience without IDE support? 

For an SDK-type app (as opposed to a company's business logic) I would go with the philosophy that every API is still defined explicitly (I think AutoValue forces this, Immutables makes it optional). This means that, e.g., for a Builder we still define all its methods as abstract methods.

This means that for all usages of the class outside that file, it's all good, no red lines since the APIs are defined. For the class itself, there will be one red line in a static method referring to the generated implementation class

https://github.com/google/auto/blob/master/value/userguide/builders.md#how-to-use-autovalue-with-builders

Here, `return new AutoValue_Animal.Builder();` is red until Gradle has ever built once (often by just running a unit test in IntelliJ).

>  And how do IDEs support them?

IntelliJ defaults to delegating builds to Gradle (which is aware of annotation processors) now so out of the box, if someone opens the project it will build fine with no tweaks. Not sure of Eclipse / VSCode, though for any IDE we are basically guaranteed to have red lines go away from running a Gradle build since unlike lombok, extra classes are generated, not replaced.

**Comment by donbeave** [comment]
I can make a switch to AutoValue, if everybody agree to use AutoValue for such case. Personally I’m big fan of Immutables, it looks less verbose than AutoValue and can do the same things (https://dev.to/cchacin/immutables-autovalue-lombok-which-one-2j33). In my opinion not need to align with opentelemetry-java in this particular case.

**Comment by trask** [comment]
You convinced me about Immutables (it did not take much :joy:). Google's AutoValue was chosen for the opentelemetry-java project by a Googler at the time, so I think reasonable for us to make an independent choice.

**Comment by anuraaga** [comment]
I generally prefer Immutables too! And while it has some cool features like prehash, I don't know if we'll use it. But I disagree about verbosity - for a project with many contributors and new ones coming, we should still err on the side of less magic. It means I think we should define the builder API - this keeps all the magic in one file, the value file, while all other code in the codebase is normal Java. In other words there's only one red line after clone like in my example, not at the usages of the class. We can write better javadoc too (more important for manual instrumentation libraries).

So I think we can use Immutables, but we should still write the builder APIs IMO. In that case, I think the verbosity advantage goes away though and we may err on the side of consistency.

**Comment by trask** [comment]
> In that case, I think the verbosity advantage goes away though and we may err on the side of consistency.

Thanks @anuraaga. That makes sense to me.

@donbeave are you still up for doing this with AutoValue? if so we will assign this issue to you 👍

**Comment by donbeave** [comment]
@trask yes, I’m in.

**Comment by piotr-sumo** [comment]
@donbeave Have you completed your work? If not, I'd like to continue from where you left.
@trask @anuraaga is help still needed for this issue?

**Comment by donbeave** [comment]
@piotr-sumo Sorry, I didn't even start to do it. If you can, please take this task. Thank you for your help!

**Comment by trask** [comment]
@piotr-sumo assigned to u!

**Comment by iNikem** [comment]
What are those classes? Can we have some examples?

**Comment by piotr-sumo** [comment]
@iNikem correct me if I'm wrong but in my opinion this is an example https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/fbe55e04aa1e01e96aec91630bc9732f5d886487/javaagent-api/src/main/java/io/opentelemetry/javaagent/instrumentation/api/db/SqlStatementInfo.java

**Comment by piotr-sumo** [comment]
@trask can we close this issue?

**Comment by mateuszrzeszutek** [comment]
Closed by #2494
