### ISSUE TITLE
Scoped context not used in Kafka Producer

### ISSUE THREAD

**Issue by imduffy15** [open-telemetry/opentelemetry-java-instrumentation#684]
I've wrapped my `producer.send` with a scope, it was my understanding this should set the context and as a result, the context's span should become the parent of the created span, however this doesn't appear to happen.

Sample code at https://github.com/imduffy15/opentelemetry-problem

**Comment by trask** [comment]
Hi @imduffy15, thanks for the excellent repro!

Which version of the opentelemetry auto javaagent are you using?

We have some weird mismatches of which version of the javaagent works with which version of the opentelemetry-api (which I keep forgetting about).

We are aligning versions with the release that is going out later today, so that this new release `0.6.0` will work (only) with `open-telemetry-api` versions `0.6.0`.

I also just submitted a PR (#687) to make document this in the README.md, with an extra ⚠️ symbol (I don't think this was doc'd anywhere previously 😞).

If you want to test out with the latest SNAPSHOT (it's called 0.5.0, but will be 0.6.0 when we release):

https://oss.jfrog.org/artifactory/oss-snapshot-local/io/opentelemetry/instrumentation/auto/opentelemetry-javaagent/

Testing your repro with the latest SNAPSHOT:

```
[2020-07-13 17:10:07,472: INFO/main] (Main.java:39) - Creating context with traceparent 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01
[2020-07-13 17:10:07,657: INFO/main] (Main.java:50) - Context created with traceId TraceId{traceId=0af7651916cd43dd8448eb211c80319c}
[2020-07-13 17:10:07,658: INFO/main] (Main.java:53) - Currect context traceId is TraceId{traceId=0af7651916cd43dd8448eb211c80319c}
[2020-07-13 17:10:33,818: INFO/main] (Main.java:76) - Wanted traceparent not found, got 00-0af7651916cd43dd8448eb211c80319c-f38404ab1a04c5ef-01
```

which shows the traceId is preserved, and you get a new spanId, which points to the PRODUCER span that the Kafka instrumentation emits

**Comment by imduffy15** [comment]
Hi @trask 

Thanks for your help! I was able to recreate what you got by using the updated agent which is fantastic and resolves this issue. Thank you.

Out of curiosity, what change resulted in the fix? I was trying to go through the code and figure it out but wasn't able to determine it.

**Comment by iNikem** [comment]
Otel-java is still, as we all, in a rapid development phase. API changes significantly from version to version. And this repo has to follow it closely in order to integrate properly. So mixing different versions of otel-java and instrumentation will most probably break tracing. Until GA, that is :)

**Comment by trask** [comment]
Hey @imduffy15, #662 is the PR that brought `opentelemetry-api` version `0.6.0` compatibility.

In particular, the changes in that PR in the `:instrumentation:opentelemetry-api-beta` module.

Basically, at runtime, we check if the instrumentation "matches" the shape of the api that we are instrumenting, and only apply the instrumentation if it matches. That's how we handle instrumenting different versions of the same library. Documenting this "matching" process will be happening in #536 (it's definitely not anywhere near obvious 😄).

**Comment by imduffy15** [comment]
Hi @trask 

Some further interesting behaviour with this and reproducible on the provided code.

```
ota.integrations.enabled = false
ota.integration.kafka.enabled = true
```

passed as a `-Dota.trace.config` results in the following output:

```
[2020-07-16 14:04:11,925: INFO/main] (Main.java:39) - Creating context with traceparent 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01
[2020-07-16 14:04:11,972: INFO/main] (Main.java:50) - Context created with traceId TraceId{traceId=0af7651916cd43dd8448eb211c80319c}
[2020-07-16 14:04:11,973: INFO/main] (Main.java:53) - Currect context traceId is TraceId{traceId=0af7651916cd43dd8448eb211c80319c}
[2020-07-16 14:04:15,560: INFO/main] (Main.java:76) - Wanted traceparent not found, got 00-7261894c5bb20f493f0d835874b9ec9c-9feba74468fa7018-01
```

note the traceparent is different.

**Comment by trask** [comment]
Hey @imduffy15,

You also need

```
ota.integration.opentelemetry-api.enabled = true
```

in order to get the OpenTelemetry API instrumentation itself (which provides interoperability with OpenTelemetry API that is brought by the application).

Can I ask your use case for enabling only specific instrumentation? That would help us understand how to document / address this better.

**Comment by imduffy15** [comment]
> in order to get the OpenTelemetry API instrumentation itself (which provides interoperability with OpenTelemetry API that is brought by the application).

Thank you, I did not figure that one out, was more suspect of the java_concurrent or classloader integrations.

> Can I ask your use case for enabling only specific instrumentation? That would help us understand how to document / address this better.

Sure, so we are introducing opentelemetry in a distributed system that communicates using Kafka. Its a mixed language environment of Java, Lua and Python. For the moment, the focus is to get all Kafka interaction in the Java components instrumented and to ensure the traceId is being passed through other components. Once that is completed we will being adding manual instrumentation and taking a look at what is available from the automatic instrumentation. Starting off the automatic instrumentation generated too much noise.

**Comment by trask** [comment]
Thanks @imduffy15, appreciate the info!
