### ISSUE TITLE
Muzzle plugin is not working unless maven repositories is declared explicitly

### ISSUE THREAD

**Issue by aaron-ai** [open-telemetry/opentelemetry-java-instrumentation#6927]
After #6796 , the default maven repository is removed, it seems that it causes the muzzle plugin unable to work as normal unless explicit maven repository is declared in each project. Is it by design?

**Comment by mateuszrzeszutek** [comment]
Hey @aaron-ai ,
After #6796 the muzzle plugin will use your `project.repositories` settings; this is by design - we want the plugin to use the same repositories that are used during other build actions that require dependency resolution, e.g. compilation. Did you make sure to add maven central there?

**Comment by aaron-ai** [comment]
@mateuszrzeszutek It means each instrumentation should add maven central to their `build.gradle.kts`?

**Comment by mateuszrzeszutek** [comment]
You need to add the repositories that you want muzzle to scan - if the artifacts that you're instrumenting are hosted on maven central, then you'll need to add maven central.

**Comment by aaron-ai** [comment]
> You need to add the repositories that you want muzzle to scan - if the artifacts that you're instrumenting are hosted on maven central, then you'll need to add maven central.

Got it, thank you!
