### ISSUE TITLE
Can I use auto instrumentation and manual instrumentation at the same time?

### ISSUE THREAD

**Issue by arloor** [open-telemetry/opentelemetry-java-instrumentation#6928]
**Is your feature request related to a problem? Please describe.**
I noticed that opentelemetry java-agent shaded io.opentelemetry.*  to io.opentelemetry.javaagent.shaded.io.opentelemetry.*
so there are two sets of classes for manual and auto instrumentation.
so  if I use auto instrumentation and manual instrumentation at the same time, trace info cannot share between auto and manul.

**Describe the solution you'd like**
trace info can share between auto and manul.

**Describe alternatives you've considered**
the point may be: in java agent, classes is loaded by bootstrap classloader（or classloaders inherit bootstrap classloader。but in manual instrumentation, classes is loaded by AppclassLoader or its sons( eg:Springboot Classloader，TomcatClassloader)。that means it is difficult to use only one set of classes, because it is diffcult to use the same classloader to loader opentelemtey api classes.

**Comment by aaron-ai** [comment]
related discuss: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/6005

**Comment by arloor** [comment]
> related discuss: #6005

that issue's answer seems to say:

1. it does have two sets of API and SDK for manual and auto
2. by default, auto instrumentation will hijack manual instrumentation by hijacking the GlobalOpenTelemetry( or a custom one)
3. or users can disable auto instrumentaiton and use manual instrumentation only.

I am interested in whether  can there be only one set of API and SDK shared by auto and manul, instead of one hijacking(or disbale) the other

**Comment by laurit** [comment]
> Can I use auto instrumentation and manual instrumentation at the same time?

Yes, you can. Just include the opentelemetry api classes in your application and write your instrumentation as you'd write it when not using the auto instrumentation agent. The only difference is that you don't need to configure the opentelemetry sdk, just use `GlobalOpenTelemetry` to get access to the sdk that is configured by the agent. Agent will bridge the openteletry api that is inside your application so all the traces will go through the agent. Spans created by agent and manual instrumentation can appear in the same trace.

> I am interested in whether can there be only one set of API and SDK shared by auto and manul, instead of one hijacking(or disbale) the other.

Current design is such that agent has its own shaded copy of the api and user application should bring its own api. I guess if you really insist you could attempt using the api that is shaded inside your application, but that is definitely not something users are intended to do.
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6902. That issue is about using unshaded api in agent jar.

**Comment by mateuszrzeszutek** [comment]
Hey @arloor ,
Did Lauri's comment answer your question?

**Comment by arloor** [comment]
> Hey @arloor , Did Lauri's comment answer your question?

yes, [this doc](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/misc/interop-design/interop-design.md#interoperability-design) does really help me.

**Comment by mateuszrzeszutek** [comment]
Great to hear that!
I'll close this issue then -- if you have any other questions, don't hesitate to open a new one.
