### ISSUE TITLE
Consistent way to set service.name for OTLP, Jaeger and Zipkin exporters?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#703]
From https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/424#issuecomment-633109742:

The current way to set service.name is a little disjointed:

For OTLP exporter:

```
export OTEL_RESOURCE_ATTRIBUTES=service.name=shopping
```

For Jaeger exporter:

```
-Dota.exporter.jaeger.service.name=shopping
```

For Zipkin exporter:

```
-Dota.exporter.zipkin.service.name=shopping
```

This may also require discussion/changes in opentelemetry-java.

**Comment by tedsuo** [comment]
This may be broader than just service names, since arbitrary resources need to be supported by all exporters. This is easy for OTLP, but confusing for Jaeger and Zipkin, which may or may not have equivalent concepts (I admit ignorance on this one). 

In addition to not supporting arbitrary resources, these formats may have native concepts which map to specific resources. `service.name` is mentioned here, but there may be more. If a user sets one of these special resources, we want to map it to the equivalent concept in zipkin or jaeger. For arbitrary resources, we want a standard transformation (for example, turning resources into span attributes).

Since this relates to data protocols, it is a cross-language issue and should be defined in the spec.

Resource transformations for Zipkin need to be added here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/zipkin.md#opentelemetry-to-zipkin-transformation

Jaeger transformations need to be added in general: https://github.com/open-telemetry/opentelemetry-specification/issues/414

**Comment by trask** [comment]
Thanks @tedsuo.

I'm going to close this, it looks like this discussion is already in the works in the specification repo (https://github.com/open-telemetry/opentelemetry-specification/pull/666).

In particular, that PR only specifies `OTEL_RESOURCE_ATTRIBUTES` for setting service name across OTLP, Jaeger and Zipkin exporters.

Plus there's a proposal for a simpler way to set the service name (which sounds really helpful @anuraaga) https://github.com/open-telemetry/opentelemetry-specification/pull/666#discussion_r445603526.
