### ISSUE TITLE
Javaagent doesn't work with java.net.spi.InetAddressResolverProvider

### ISSUE THREAD

**Issue by hermannpencole** [open-telemetry/opentelemetry-java-instrumentation#7130]
I use  opentelemetry-javaagent - version: 1.19.2 :
INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.19.2

I work with java 18 because i need InetAddressResolverProvider : https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/net/spi/InetAddressResolverProvider.html. 
When I launch my app without opentelemetry-javaagent the InetAddressResolverProvider  works.
When I launch my app with opentelemetry-javaagent the InetAddressResolverProvider doesn't works.

**Comment by mateuszrzeszutek** [comment]
The agent probably loads the resolver first, using the agent classloader (not the system CL, as the Javadoc suggests): https://github.com/openjdk/jdk/blob/f2acdfdcbd2a49c1167656e73b67b38b545f9472/src/java.base/share/classes/java/net/InetAddress.java#L477-L482
We might need to fix the CL before OpenTelemetry is initialized (it most likely resolves the exporter endpoint address)

**Comment by hermannpencole** [comment]
Tks for your help mateuszrzeszutek : with your comment i found a workaround.
I extract code from my InetAddressResolverProvider into a new jar. And I declare this jar in launch option **-Xbootclasspath/a**

**Comment by serkan-ozal** [comment]
This issue is similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10921

I have propose the following solution: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10921#issuecomment-2267085547

What do you think about it @mateuszrzeszutek @laurit

**Comment by laurit** [comment]
@serkan-ozal you are welcome to create a PR. If I were to attempt solving this I'd probably attempt transforming the `InetAddress` class so that instead of `if (VM.isBooted())` it would have something like `if (VM.isBooted() && AgentBooted.initialized)` the `AgentBooted.initialized` flag could be set after agent initialization has completed. The transformation would need to be set up before we initialize opentelemetry sdk. Could do something similar to `LaunchHelperClassFileTransformer`.

**Comment by serkan-ozal** [comment]
Hmm, thanks for pointing out. Will check `LaunchHelperClassFileTransformer`

**Comment by serkan-ozal** [comment]
@laurit Here it is: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11987
