### ISSUE TITLE
How best to capture response attributes in HttpServerTracer

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#733]
Opening this to track issue raised at https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/726#discussion_r456943732

One option to start discussion:

* Add a fourth(?!??) generic parameter to HttpServerTracer:

   <pre>
   HttpServerTracer&lt;REQUEST, <b>RESPONSE</b>, CONNECTION, STORAGE&gt;
</pre>

* Pass `RESPONSE` in to `end`/`endExceptionally` instead of `responseCode`
* Add `protected abstract getResponseCode(RESPONSE)` to HttpServerTracer, and call `getResponseCode` from HttpServerTracer's `end`/`endExceptionally`
* Override `end`/`endExceptionally` in HttpServerTracer subclasses when we want to capture response attributes

**Comment by anuraaga** [comment]
Ah yeah this came to mind randomly. I think `RESPONSE` is required for most instrumentation and would add it as a parameter. I feel as if CONNECTION and STORAGE can be merged into REQUEST or RESPONSE somehow though I haven't given it detailed thought.

**Comment by anuraaga** [comment]
For reference, we've run into corner cases in brave for things that feel like they should be part of request, but end up not being known until processing and because of the instrumented library not available at first, so we add them to response, like the route (`/users{userId}` type of URL)
https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpResponse.java#L69
