### ISSUE TITLE
Getting Kafka consumer & producer interceptors in auto-instrumentation

### ISSUE THREAD

**Issue by Ipuvi** [open-telemetry/opentelemetry-java-instrumentation#7402]
Hi
I'm using auto-instrumentation javaagent jar in my application but using kafka as well in my application, I want to use kafkaTracing consumer and producer interceptors while committing/beginning transaction, is it possible to do this?
Can someone please help?
#HelpWanted

**Comment by mateuszrzeszutek** [comment]
Hey @Ipuvi ,
The javaagent already includes a Kafka instrumentation; is that not working for you?

**Comment by Ipuvi** [comment]
That works, but I want to create tracingInterceptors with producer and consumer and use them in my application code. Is there a way to get this done along with auto-instrumentation?

**Comment by mateuszrzeszutek** [comment]
That would most likely work, but I'm not sure I understand why you want to do it - the javaagent provides the same instrumentation as `KafkaTracing` (actually the javaagent instrumentation covers a bit more edge cases), so if you add it there either won't be any effect (duplicate telemetry will be suppressed), or you might get disjoint/inaccurate telemetry (in the aforementioned edge cases, where the javaagent and library instrumentation might interfere with each other).

**Comment by Ipuvi** [comment]
I was trying this as I wanted to add some custom tracing data, and also want to use that in events published/committed.

**Comment by mateuszrzeszutek** [comment]
I see, that's certainly a valid reason.

For the producer side, you actually have to use the `KafkaTelemetry` class. But, instead of an interceptor, I'd recommend using [`KafkaTelemetry#wrap()`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/kafka/kafka-clients/kafka-clients-2.6/library/src/main/java/io/opentelemetry/instrumentation/kafkaclients/KafkaTelemetry.java#L83) - it wraps the entire send operation in a span, and I think it will play nicely with the agent instrumentation and suppress it, so that you don't get duplicate telemetry.

For the consumer side, you could try using `Span.current()` to access current consumer span - and then add whatever extra data you need. I'd recommend avoiding the `KafkaTelemetry` library instrumentation in this case: Kafka consumer API is rather unfriendly when it comes to instrumentation (because it's a polling API), and the library instrumentation is **very** limited in its functionality.

**Comment by Ipuvi** [comment]
Sure, Let me try this and get back.

**Comment by Ipuvi** [comment]
Hey
I tried but was confused between two things, what's the difference between `Span.wrap()` and `Span.fromContext()`. Also, `Span.fromContext()` expects `Context` type argument, even tracer.setParent expects same, but how to build Context using traceId and spanId.

**Comment by mateuszrzeszutek** [comment]
Can you share your code? And explain in a bit more detail what exactly you're trying to achieve?

**Comment by Ipuvi** [comment]
Hey @mateuszrzeszutek 
I was able to wrap the entire send to one trace as suggested but was trying one more thing, is it possible to connect send and receive spans under one trace?

**Comment by mateuszrzeszutek** [comment]
In most cases it should; also take a look at my post in the other thread: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7464#issuecomment-1398581306
