### ISSUE TITLE
Join span with a custom new span in auto-instrumentation

### ISSUE THREAD

**Issue by Ipuvi** [open-telemetry/opentelemetry-java-instrumentation#7464]
Hi Team
I'm using auto-instrumentation but we have a poller which would have spans related to a trace, I am using auto-instrumentation-java, is it possible to join a new span to the by fetch a span with some traceId in auto-instrumentation?
Can someone help?
TIA!!

**Comment by laurit** [comment]
As far as I understand you are asking how to make spans created by the agent be part of some trace. The trace the span is part of is determined by the parent span and parent span is read from context. So you'll just have to set the context with desired parent span around the code that creates the spans.

**Comment by mateuszrzeszutek** [comment]
Hey @Ipuvi,
Have you tried what Lauri suggested above?

**Comment by Ipuvi** [comment]
Hey @mateuszrzeszutek 
I tried what Lauri suggested and it seems to be working at a few places but for Kafka Consumer traces I'm still getting disjoint traces, and still unable to connect them.

**Comment by masonedmison** [comment]
Hi @mateuszrzeszutek and @laurit 
I am facing a similar issue regarding `Consumer`s . Basically I am "wrapping" a consumer like 
```java
myConsumer = kafkaTel.wrap(new KafkaConsumer<>(properties))
```
As far as I can tell, calling `wrap` creates a proxy instance which when the `poll` method is called then calls `buildAndFinishSpan` meaning that calling `Span.getCurrent()` will not work since the `.end` has been called on the `Span` created by the wrapped `Consumer`. 

My question then is how would I get the context of the span created by the wrapped consumer so that I can provide that as a parent span to continue the trace?

**Comment by mateuszrzeszutek** [comment]
Unfortunately, in Kafka's case, you pretty much have to either use javaagent (which also isn't perfect, I'm afraid; there are numerous issues in this repo about leaking context from Kafka consumer apps), or implement the consumer part manually. 
We really can't do much with polling APIs, they're almost impossible to instrument correctly. We cannot set the consumer span as current because we have no idea when to end that span; it really depends on the design of the instrumented application.
If it's possible in your application, I really recommend using some kind of wrapper over Kafka consumer API - we have instrumentations of both Spring Kafka and Vertx Kafka which do not exhibit the context leaking issues.

**Comment by masonedmison** [comment]
@mateuszrzeszutek Thanks for the update. Hm. Spring kafka could definitely be an option for us as this is a `Spring` application. I assume [this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring/spring-kafka-2.7) would be the corresponding `open-telemetry` interop for Spring kafka?

**Comment by mateuszrzeszutek** [comment]
Yes, exactly that one.
Also, you can find an example of setting up both the producer and consumer instrumentation to work together (context propagation included) in our tests: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0223dc3a287546ea64fd213d28b3d3a779af48b8/instrumentation/spring/spring-kafka-2.7/library/src/test/java/io/opentelemetry/instrumentation/spring/kafka/v2_7/SpringKafkaNoReceiveTelemetryTest.java#L37-L56

**Comment by mateuszrzeszutek** [comment]
Hey @Ipuvi ,
It seems that Lauri's comment has helped you a bit; let's continue the remaining Kafka discussion in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7402.
I'll close this issue, please reopen it if there's anything more you'd like to ask.
