### ISSUE TITLE
slf4j (logback) logs not getting forwarded to open-telemetry-collector by OpenTelemetryAppender

### ISSUE THREAD

**Issue by ff-sdesai** [open-telemetry/opentelemetry-java-instrumentation#7723]
I have created a spring-boot micro-service with spring-cloud-sleuth. I have also configured a open-telemetry-collector to forward the logs to datadog. The otel-collector is running in a docker container along with the micro-service. I have configured io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender in logback.xml file to forward the logs also to otel-collector along with traces. However, in datadog, I can only see traces and not logs. The logs printed are using the same traceId and spanId as that of trace. But due to some unknown reason, otel-collector is not exporting logs like it is exporting traces.

This issue can be reproduced using a POC with very few files and is uploaded at https://github.com/ff-sdesai/distributed-tracing-spring. The readme.md has the steps to run the application. You will need to enter a valid datadog API key in the .env (hidden) file.I will not be able to share the key since the key is specific to my organization.
Please let me know if there is something else that I should specify along with these details.

I am using docker image otel/opentelemetry-collector-contrib:0.70.0 and Ubuntu 22.04.1 LTS.

**Comment by trask** [comment]
hi @ff-sdesai!

can you narrow down the issue to one of these components so we can get this issue to the appropriate folks/repository?

* OpenTelemetry Java Instrumentation
* OpenTelemetry Collector
* OpenTelemetry Collector DataDog Exporter
* DataDog Ingestion

**Comment by ff-sdesai** [comment]
Opentelemetry collector is not receiving the logs sent by the application. I confirmed this by sending logs to otel-collector using curl and it works fine.
So, it looks to be an issue with OpenTelemetry Java `Instrumentation(io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender)`

**Comment by laurit** [comment]
Firstly in https://github.com/ff-sdesai/distributed-tracing-spring/blob/main/spring-cloud-sleuth-otel-slf4j/src/main/resources/logback.xml#L13 you are using `io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender` this is the appender for mdc instrumentation. For exporting logs you'll need `io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender`.
Secondly in https://github.com/ff-sdesai/distributed-tracing-spring/blob/ee36dcd78ce9c0b517355642af3c5e0b8b6d67d0/spring-cloud-sleuth-otel-slf4j/src/main/resources/logback.xml#L17 you should use the appender for it to have any effect.
Thirdly in https://github.com/ff-sdesai/distributed-tracing-spring/blob/main/spring-cloud-sleuth-otel-slf4j/pom.xml you have
```
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-otlp-trace</artifactId>
			<version>1.14.0</version>
		</dependency>
```
you don't need this, you already have dependency to a newer version of `opentelemetry-exporter-otlp`. Also
```
		<dependency>
			<groupId>io.opentelemetry.instrumentation</groupId>
			<artifactId>opentelemetry-logback-1.0</artifactId>
			<version>1.9.2-alpha</version>
			<scope>runtime</scope>
		</dependency>
```
is for mdc instrumentation. If you need it then please try to align the version with the rest of the otel artifacts. You'll need to add
```
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-otlp-logs</artifactId>
			<version>1.22.0-alpha</version>
		</dependency>
```
Finally see https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library#usage You'll have to configure the `GlobalLoggerProvider`. Try adding
```java
        LogRecordExporter otlpGrpcLogRecordExporter =
                OtlpGrpcLogRecordExporter.builder()
                        .setEndpoint("http://localhost:4317")
                        .build();
        SdkLoggerProvider sdkLoggerProvider =
                SdkLoggerProvider.builder()
                        .addLogRecordProcessor(SimpleLogRecordProcessor.create(otlpGrpcLogRecordExporter))
                .build();
        GlobalLoggerProvider.set(sdkLoggerProvider);
```
to the start of the main method. There probably is a way to get `SdkLoggerProvider` from spring configured otel sdk. If you don't have collector running you should now see lines like `13:26:29.851 [OkHttp http://localhost:4317/...] ERROR i.o.e.i.grpc.OkHttpGrpcExporter serviceName:  requestId:  trace_id:  span_id:  - Failed to export logs. The request could not be executed. Full error message: Failed to connect to localhost/0:0:0:0:0:0:0:1:4317
`

**Comment by ff-sdesai** [comment]
Thanks @laurit  for pointing out the incorrect configuration. I added the configuration as you suggested. Only difference being instead of setting endpoint as `http://localhost:4317`, I configured it as `http://otel-collector:4317` and now I am getting following error:-
`Str(I/O error on GET request for "http://172.22.0.1:8282/": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused))`
It is trying to connect to `http://172.22.0.1:8282`, whereas it should be `http://otel-collector:8282`. Any additional configuration I can do to change this URL?

**Comment by ff-sdesai** [comment]
@laurit  Please ignore my previous comment (which I have deleted). I am checking if the configuration suggested by you is working for me. Will update here soon

**Comment by ff-sdesai** [comment]
@laurit I did not understand the second point you said. After doing remaining changes, I am now getting following error:-
`ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an AppenderAttachable at the top of execution stack. Near [appender-ref] line 19`
Looks like it is not able to find a property appender-ref in io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender. Any suggestions what can be done here?

**Comment by ff-sdesai** [comment]
Thanks @laurit for your help . I can see the logs in datadog now

**Comment by TanishqDhussa** [comment]
@laurit I am using the same otel appender :
This is the logback.xml file :
`<configuration>

    <property name="pod" value="RainForest"/>
    <property name="service" value="FirstFuel_legacy_application"/>
    <property name="env" value="dev"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} serviceName: ${pod} requestId: %X{requestId} pod: ${pod} service: ${service} env: ${env} - %msg%n</pattern>
        </encoder>
    </appender>
    
    <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender">
    </appender>

    <root level="INFO">
        <appender-ref ref="OTEL" />
        <appender-ref ref="STDOUT" />
    </root>

</configuration>
`
This is the configuration file:
`package com.example.demo;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.opentelemetry.exporter.otlp.logs.OtlpGrpcLogRecordExporter;
import io.opentelemetry.sdk.logs.SdkLoggerProvider;
import io.opentelemetry.sdk.logs.export.LogRecordExporter;
import io.opentelemetry.sdk.logs.export.SimpleLogRecordProcessor;

//import io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter;
//import io.opentelemetry.sdk.trace.export.SpanExporter;

@Configuration
public class OtelConfigurations {
    
    @Bean
    public LogRecordExporter otlpGrpcLogRecordExporter() {
        try {
            return OtlpGrpcLogRecordExporter.builder()
                    .setEndpoint("http://localhost:4317")
                    .build();
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
            throw new RuntimeException("Error creating LogRecordExporter bean", e);
        }
    }

    @Bean
    public SdkLoggerProvider sdkLoggerProvider(LogRecordExporter otlpGrpcLogRecordExporter) {
        try {
            return SdkLoggerProvider.builder()
                    .addLogRecordProcessor(SimpleLogRecordProcessor.create(otlpGrpcLogRecordExporter))
                    .build();
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
            throw new RuntimeException("Error creating SdkLoggerProvider bean", e);
        }
    }

}
`
This is a ref to the spring boot application file :
`package com.example.demo;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import io.opentelemetry.exporter.otlp.logs.OtlpGrpcLogRecordExporter;
import io.opentelemetry.sdk.logs.SdkLoggerProvider;
import io.opentelemetry.sdk.logs.export.LogRecordExporter;
import io.opentelemetry.sdk.logs.export.SimpleLogRecordProcessor;
import io.opentelemetry.api.logs.GlobalLoggerProvider;

@SpringBootApplication
public class OtelCollectorApplication {

	public static void main(String[] args) {
		
		
		System.out.println("Starting Application.....");
		
		// Create an application context
        AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext(OtelConfigurations.class);

        SdkLoggerProvider sdkLoggerProvider = applicationContext.getBean(SdkLoggerProvider.class);

        GlobalLoggerProvider.set(sdkLoggerProvider);

	    Logger logger = LoggerFactory.getLogger(OtelCollectorApplication.class);
	    SpringApplication.run(OtelCollectorApplication.class, args);
		
		logger.info("Info Logs..........modified");
		logger.debug("debug logs................");
		logger.warn("warning log.......");
		logger.info("New Logs");
		logger.info("Rainforest: service.pod={}, service.name={}, deployment.environment={}, service.version={}",
                "sre", "oe", "dev", "1.0");
		logger.info("additional log");
		//logger.info("Additinal logs");
		
		applicationContext.close();
	}

}
`
I am getting proper logs on datadog : 
`
Jan 04 15:54:09.000
{"name":"unknown_service:java"}
New Logs

Jan 04 15:54:09.000
{"name":"unknown_service:java"}
Started OtelCollectorApplication in 1.032 seconds (JVM running for 1.567)

Jan 04 15:54:09.000
{"name":"unknown_service:java"}
Info Logs..........modified

Jan 04 15:54:09.000
{"name":"unknown_service:java"}
Tomcat started on port(s): 8081 (http) with context path ''

Jan 04 15:54:09.000
{"name":"unknown_service:java"}
Starting ProtocolHandler ["http-nio-8081"]

Jan 04 15:54:09.000
{"name":"unknown_service:java"}
Initializing Spring embedded WebApplicationContext`

I was planning to add a few tags to logs that are forwarded to datalog via : 
So I modified the logback.xml file to add tags : 

Option 1:
`    <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender">
        <layout>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} serviceName: 'Demo' requestId: %X{requestId} pod: '${pod}' service: '${service}' env: '${env}' - %msg%n</pattern>
        </layout>
    </appender>`
    
 option 2:
 `    <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender">
        
        <tags>
            <tag key="pod" value="${pod}" />
            <tag key="service" value="${service}" />
            <tag key="env" value="${env}" />
        </tags>
    </appender>`
    
    
    I modified the Otel appender using both the options, but getting the encoder exception:
    
    Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:15 - no applicable action for [tags], current ElementPath  is [[configuration][appender][tags]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@16:45 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@17:53 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:45 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:179)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:232)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:329)
	... 18 common frames omitted
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:15 - no applicable action for [tags], current ElementPath  is [[configuration][appender][tags]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@16:45 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@17:53 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:45 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:344)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.example.demo.OtelCollectorApplication.main(OtelCollectorApplication.java:31)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:15 - no applicable action for [tags], current ElementPath  is [[configuration][appender][tags]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@16:45 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@17:53 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:45 - no applicable action for [tag], current ElementPath  is [[configuration][appender][tags][tag]]
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:179)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:232)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:329)
	... 18 more
