### ISSUE TITLE
Added KTor plugin, but tracing is being suppressed

### ISSUE THREAD

**Issue by anderssv** [open-telemetry/opentelemetry-java-instrumentation#7755]
Hi,

I am trying to get the KTor (server, alpha) plugin working. I have added the library, and the agent on the command line. I have also validated that is is loaded (globally) _without_ a noop implementation.

Do I have to set up each endpoint in KTor specifically? Or add another setting to enable endpoint traces? I want all endpoints to be recorded automatically and was hoping adding the plugin and agent would be enough.

Through debugging the code I have found that the plugin does not trigger on a endpoint because suppressed = true. But I have a hard time to understand what the basis of the suppression is? Span type seems to be 'SERVER' and the trace implementation id is 'io.opentelemetry.ktor-2.0'.

What am I doing wrong? :) I might have the wrong model as I am coming from the New Relic agent where you don't need to setup anything else...?

Thanks :)

**Comment by anderssv** [comment]
Alright, so a bit more digging around. Seems it makes sense that the span is suppressed, when I do -Dotel.instrumentation.experimental.span-suppression-strategy=none it is no longer suppressed. I guess the Jetty span is already started and that is why the KTor span is suppressed.

But then I think I get to the real issue here: It seems that the naming is just done with "HTTP " + METHOD. I am really looking for a way to get something like "GET /api/status/{id}", so basically the KTor route name. But it seems the KTor implementation has naming locked down to HttpSpanNameExtractor? Or am I misreading something?

**Comment by laurit** [comment]
You are correct, nested spans for the same operation are suppressed. For example if you have a http client that wraps another http client and both are instrumented then the span from wrapped client is suppressed. Similarly if 2 frameworks generate a SERVER span the later one is suppressed. 
Jetty span is named `HTTP {method}` because jetty instrumentation doesn't know anything about ktor and its routes. For ktor we currently only have library instrumentation that is not included in the agent. In agent instrumentation I think we wouldn't need the part that creates the SERVER span as it is probably also created by some other instrumentation. What we need for the agent instrumentation is the part that adds the http route, which should be
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2e2e891855251eab2d48a61b32e97ba714fe7208/instrumentation/ktor/ktor-2.0/library/src/main/kotlin/io/opentelemetry/instrumentation/ktor/v2_0/KtorServerTracing.kt#L159-L164
Here instead of `call.attributes.getOrNull(contextKey)` you'd need to use `Context.current()` and the null check isn't needed also. I guess you could build your own instrumentation where you only use the bit that updates the route and use it instead of the ktor instrumentation and it should do what you want. If you so wish you could also contribute this to the javaagent.

**Comment by trask** [comment]
> For ktor we currently only have library instrumentation that is not included in the agent.

@anderssv if you are interested in contributing ktor javaagent instrumentation that would be very welcome!

**Comment by anderssv** [comment]
I might give the javaagent a try later but it is a bit bigger task. I would love to if I can find the time. Thanks to the clarifications from @laurit , I got it working with the javaagent doing this:

```
install(createApplicationPlugin(name = "KtorOpentelemetryNamingPlugin") {
        on(MonitoringEvent(Routing.RoutingCallStarted)) { call ->
            HttpRouteHolder.updateHttpRoute(Context.current(), HttpRouteSource.SERVLET, { _, arg -> arg.route.toString() }, call)
        }
})
```

Can I ask another question that is borderline related? I think it is relevant for doing it via the javaagent as well: I would like to start a span for some background batches we are running (TimerTask). Anyone able to spot why this isn't working? Fairly new to Opentelemetry so probably some misunderstanding on my part... 

```
GlobalOpenTelemetry.get().tracerProvider.tracerBuilder("OurBatches").build().spanBuilder("batchName").startSpan()
```

And then a `span.end()` in a finally block. It doesn't seem to be reported alongside the KTor transactions that we have?

**Comment by anderssv** [comment]
Oh yeah, just for anyone popping by later: I think the KTor code above relies on auto instrumentation. It works because an existing span is started for the Jetty engine we use. Opentelemetry also supports Netty (the KTor default usually) so it should work with that as well.

**Comment by anderssv** [comment]
Found a working way for batches through this: https://slack-chats.kotlinlang.org/t/488833/is-anyone-here-familiar-with-the-open-telemetry-kotlin-imple

And had to set the Kind to SERVER as New Relic filters the other kinds by default. Not sure what the "correct" kind is though. :)

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind `INTERNAL` should be the correct choice. The thing you should be aware of when using other types like `SERVER` is that the agent contains logic to suppress nested `SERVER` spans, there is a flag to disable this suppression.

**Comment by anderssv** [comment]
Thanks for the details and link. It is not suppressed now because there is actually no "wrapping" `SERVER` call. These are `TimerTasks` that runs as batches in the background. I can see that the specification for SERVER is "wrong" in this instance, but not sure `PRODUCER` would fit either. `INTERNAL` is of course the default and could work, but it is also interesting for us to have something like "a processing transaction, but from a batch" to represent and track what is happening. Would you still use `INTERNAL`?

I see that choosing to filter away internal is definitely a New Relic choice, but it seems that there should be something to "elevate" the initiating span. :)
