### ISSUE TITLE
HttpServlet Tag Enhancements

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#776]
I think we should also tag headers, query params, and maybe fragments in the servlet spans. I'd be happy to implement this.

**Comment by trask** [comment]
hey @FrankSpitulski! I forgot about https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v0.6.0/agent-bootstrap/src/main/java/io/opentelemetry/auto/bootstrap/instrumentation/decorator/HttpServerTracer.java#L133, see if this is what you are looking for around query params/fragments

**Comment by trask** [comment]
for http headers, are you looking to capture standard headers like http host and user agent, or others?

**Comment by FrankSpitulski** [comment]
That is exactly what I'm looking for. Standard headers are good. I'd also like to tag the rest of them if possible. Looking at the query parameter setting, maybe it can be similar such as a verbose headers flag.

**Comment by trask** [comment]
i just realized that query param/fragment are already part of `http.url`. do you need those captured separately as well? i'm kind of wondering if we can drop those config settings i linked to above (and associated attributes), since they aren't defined by the [http semantic attributes spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes)

for standard headers, there's a couple of headers (Host, User-Agent) already spec'd out that we definitely want to capture

for capturing all headers, what would you propose for the span attribute name / value format? also, ideally we'd like to go through the spec process for new span attributes like this

in the meantime, if we want to go through spec process for this, we've been discussing the ability to subclass the `HttpServerTracer` implementations in custom builds of the javaagent which could be used to implement additional behavior like this

**Comment by FrankSpitulski** [comment]
It's helpful to have them as separate tags so I'd like to keep that behaviour. For the name value pairs I'd suggest http.headers.{header}.

**Comment by FrankSpitulski** [comment]
What sort of plans are there for this subclassing? Will users have to fork and repackage the repo?

**Comment by iNikem** [comment]
I am very reluctant of adding all headers as span attributes. They may contain sensitive data such as authorisation tokens and even password in case of Basic Auth. It will not be trivial to know which headers to skip.

**Comment by iNikem** [comment]
> What sort of plans are there for this subclassing? Will users have to fork and repackage the repo?

We want to provide a way for vendors (or anybody in fact) to build their own distribution of instrumentation agent, bundled with custom functionality. Adding custom headers is one of the standard use-cases we want to support.

**Comment by trask** [comment]
So, no forking. Instead, the ability to create your own project that consumes opentelemetry-javaagent as a dependency, along with your custom stuff, and produce your own agent jar.

For subclassing the HttpServerTracer specifically, we want to have some kind of lookup (SPI) so when we instantiate those singletons, you can provide your own subclass.

**Comment by FrankSpitulski** [comment]
That sounds pretty reasonable. I'll give the standard headers a go in the meantime.

**Comment by iNikem** [comment]
Do you want to add them only for servlet based spans or for all SERVER spans? What are standard headers? `Authorization` is a standard http header that we should NOT record.

**Comment by FrankSpitulski** [comment]
I was planning on adding them in the http server tracer, not sure if that covers all server spans or if there are non http servers instrumented. I'll refer to the spec for which headers to cover.
