### ISSUE TITLE
Maven example to add extended agent 

### ISSUE THREAD

**Issue by kokikathir** [open-telemetry/opentelemetry-java-instrumentation#7850]
I m writing my own extension with maven and I wanted to embed the extension and create a single jar. I saw an example in [https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md#embed-extensions-in-the-opentelemetry-agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md#embed-extensions-in-the-opentelemetry-agent ) but this is in gradle. Does any one have an example for maven?

**Comment by mateuszrzeszutek** [comment]
Hey @kokikathir ,
We don't have a Maven example. The extension and distro examples [use several custom Gradle plugins](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f3a58b25245ba52d32ae2311d423cb015e955c82/examples/extension/build.gradle#L16-L17) that we publish, and these don't have Maven counterparts.

**Comment by iamtakingiteasy** [comment]
Does that mean it is not meant to be possible to extend instrumentation for maven-based projects?

**Comment by iamtakingiteasy** [comment]
@mateuszrzeszutek it looks like those plugins are muzzle-related. Is there a way to disable that feature in runtime, or otherwise make it possible to configure instrumentation from a module/artifact produced by maven-based project?

**Comment by iamtakingiteasy** [comment]
After some debugging, I can see now that contrary to what https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/muzzle.md documentation states, muzzle plugins are entirely optional.

If `InstrumentationModule` implementation does not implement `InstrumentationModuleMuzzle`, it is treated as always matching, hence those two plugins providing generated `InstrumentationModuleMuzzle` implementation as well as build-time checking of `InstrumentationModuleMuzzle` matching are irrelevant to this issue and are not in themselves a roadblock to maven example/extensions existence.

It should also be noted that `InstrumentationModule#typeInstrumentations` call and all subsequent calls on `TypeInstrumentation` implementation cannot be inspected in JVM debug, likely due to runtime instrumentation happening, so their execution can only be confirmed by logging.

**Comment by mcarleio** [comment]
I wrote a solution for Maven here: https://stackoverflow.com/questions/75487349/maven-example-to-add-extended-agent/78021599#78021599

In short: Use the `maven-assembly-plugin` to build a JAR based on `opentelemetry-javaagent` and put your customization JAR into the `/extensions` directory.
