### ISSUE TITLE
Advice on injecting advice into app classloader

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#796]
I noticed we're currently injecting `Servlet3Advice` here

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/servlet/servlet-3.0/src/main/java/io/opentelemetry/auto/instrumentation/servlet/v3_0/Servlet3Instrumentation.java#L60

for this helper method

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/servlet/servlet-3.0/src/main/java/io/opentelemetry/auto/instrumentation/servlet/v3_0/Servlet3Advice.java#L105

I think we generally avoid adding helpers to advice, since it seems like not a great idea to inject bytebuddy classes into an app. If this is a correct statement, we need to document it.

**Comment by trask** [comment]
> I think we generally avoid adding helpers to advice

👍 opened #801 to remove the existing ones (looks like we do this in a couple other places too)

> it seems like not a great idea to inject bytebuddy classes into an app

The advice tends to only depend on bytebuddy annotations and not bytebuddy classes, which is why `muzzle` isn't complaining like it does when we accidentally reference a static field in the Instrumentation class (which then pulls in bytebuddy classes which makes muzzle fail).

> we need to document it

I added documentation tag to track that on this issue

**Comment by trask** [comment]
I think we can close this since helper class list is auto-generated now
