### ISSUE TITLE
Allow flushing spans on shutdown using a runtime shutdown hook.

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#797]
Users on a FAAS like lambda will need to flush spans directly without batching or the function will often be terminated before it has a chance to flush.

**Comment by trask** [comment]
Command line apps often have this issue of losing telemetry at shutdown too.

What do you think about flushing in a shutdown hook instead (ideally synchronous flushing capped at some number of seconds)?

**Comment by anuraaga** [comment]
Ah yeah that sounds like a good idea, we could probably do that by default.

**Comment by iNikem** [comment]
@anuraaga if you agree with Trask's proposal, then maybe rename this task?

**Comment by wangzlei** [comment]
Adding a shutdown hook does resolve the flush issue in normal JVM but does not make sense in AWS Lambda. I did some tests in Lambda java runtime, the shutdown hook is swallowed after user's Lambda function exists. We may still want to config the SimpleSpanProcessor in auto-instrumentation.
My test code in AWS Lambda:
```
public class Handler implements RequestHandler<SQSEvent, String>{
  @Override
  public String handleRequest(SQSEvent event, Context context)
  {
    Runtime.getRuntime().addShutdownHook(new Thread() {
      @Override
      public void run() {
        System.out.println("Shutdown Hook called.");
      }
    });

    new Thread() {
      public void run() {
        int i = 0;
        while(true) {
          System.out.println(" ====" + i++);
          sleep(1000);
        }
      }
    }.start();

    System.out.println("Shutdown Hook test");
    ... ...
    ... ...
    return new String();
}
```

The log shows no `Shutdown Hook called.` and the infinite loop print is also stopped after function exits. Seems the AWS Lambda java Runtime behavior is something like a Java main() but not exactly same. 
SimpleSpanProcessor might be the solution to flush data before the function exits.

**Comment by anuraaga** [comment]
@wangzlei Can you clarify "the Lambda java Runtime still live and waits for the next request"? If the runtime is alive, doesn't that mean that the batch span processor would get to export the span using its normal scheduled execution? Or is this a special state where it's still alive but not running, maybe like a hibernated computer?

**Comment by wangzlei** [comment]
Well, Lambda environment works as a black box for us, something we known from the test and Lambda public doc that:
1. It is inefficient to launch a new JVM for each Lambda function handler invocation, the JVM is still alive to consume the upcoming events after the current Lambda function exits. Shutdown hook would not be invoked in time. 
In another word, Lambda function handler works in the worker thread in a JVM, consumes the event from a queue.

 2. Lambda freezes the execution environment if no new requests. If Lambda function finished processing the last event and the event queue is empty, not only blocks the worker thread, Lambda will use cgroup freezer to pause the docker container. Ref [dock pause](https://docs.docker.com/engine/reference/commandline/pause/). The frozen status can be over hours until new request coming or Lambda platform think it is OK to release this container.

All processes running in container frozen by cgroup freezer are suspended, also the timer in JVM. That is the reason some users complain telemetry data lost in AWS Lambda. To resolve this case we need to flush the data out synchronously.




2. To be stateless, The resources created in Lambda function handler are destroyed when function exists, even the objects are created on heap. For example the `new Thread()` I created for infinite print number, the log shows no number print after Lambda function handler exits. So OpenTelemetry components initialized in Lambda function handler like batch span processor will be destroyed when function handler exits. In this case, calling `shutdown()/forceFlush()` in destructor method might be an idea. Need to verify `finalize()` in AWS Lambda.
3. To enable auto-instrumentation by java agent is another story, because the OpenTelemetry components are generated outside of Lambda function handle, their scope are the whole JVM. That carries a trouble that if the Lambda freezes the execution environment when no new requests, the telemetry data buffered in batch processor not be sent out yet would be hold for over hours, until the environment is unfrozen. Ref [dock pause](https://docs.docker.com/engine/reference/commandline/pause/)

**Comment by trask** [comment]
`SimpleSpanProcessor` still isn't going to give synchronous flushes anymore with https://github.com/open-telemetry/opentelemetry-java/pull/1428, so can still leave you with lost telemetry data

**Comment by wangzlei** [comment]
So, neither shutdown hook nor SimpleSpanProcessor solve telemetry data lost in AWS Lambda. 
Let's keep the title 'Allow flushing spans on shutdown using a runtime shutdown hook', at least it is useful in short lifetime program.

**Comment by trask** [comment]
done(!)

**Comment by hertzsprung** [comment]
@trask lpease can you elaborate on what was done?

**Comment by trask** [comment]
hi @hertzsprung! the lambda instrumentation calls `forceFlush()` at the end of each request, if this isn't working for you can you open a new issue for it? thx
