### ISSUE TITLE
OpenTelemetry Automatic instrumentation  - Question about kafka-client

### ISSUE THREAD

**Issue by t-saito-dev** [open-telemetry/opentelemetry-java-instrumentation#8309]
Hello, thanks for this useful software !

I have a question about kafka-client's auto-instrumentation.

Looking at the code below

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/37b4a082465deff933726a42c1e4b074cb4f9b31/instrumentation/kafka/kafka-clients/kafka-clients-0.11/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/kafkaclients/v0_11/TracingList.java#L128

It is commented as "TODO: the API for ListIterator is not really good to instrument it in context of Kafka Consumer so we will not do that for now" and looks like it's not being instrumented.

Could you tell me why?

**Comment by laurit** [comment]
The instrumentation that creates spans tries to wrap the operation, start the span when the operation starts and end it when the operation ends. In the kafka apis that return an `Iterator` span is started on iterator `next` and ended on `hasNext`. This really isn't ideal as the user could skip calling `hasNext` or do stuff that isn't related to processing the message in between these calls. In contrast in a listener based interface message processing is done in `onMessage` method and it is clear when the processing starts and ends. We like that a lot more. We don't like the iterator instrumentation because it is not reliable, it could work nicely if user does not do weird things, but it could also fail if user uses the iterator in an unexpected way. Now the thing was bad with `Iterator`, with `ListIterator` it is worse as you would also need to handle backwards iteration. This far nobody has expressed interest in instrumenting `listIterator`. If needed this could be done the same way as we instrument the iterator.

**Comment by t-saito-dev** [comment]
Thank you for your quick response.

I was trying auto-instrumentation for a spark streaming application for kafka, and I asked because listIterator was used in kafka consume processing. (below code)

https://github.com/apache/spark/blob/1c057f5959c922ff59fd7648ece0dbe9a16aa286/connector/kafka-0-10/src/main/scala/org/apache/spark/streaming/kafka010/KafkaDataConsumer.scala#L210

> If needed this could be done the same way as we instrument the iterator.

Thank you, I will try it with reference to the iterator implementation.
