### ISSUE TITLE
OpenTelemetry Javaagent failed to start. [ java.security.KeyStoreException ]

### ISSUE THREAD

**Issue by Stardust002** [open-telemetry/opentelemetry-java-instrumentation#8316]
HI,

I tried several otel releases on my new linux OS but all of it looks like failed to start on this environment .  I think maybe it is due to the Linux kernel version or jdk incompatibility. I'm not sure, and the error log like this:

![微信图片_20230419155559](https://user-images.githubusercontent.com/75619600/233007850-ddb200a9-a230-4889-aeea-30652634b52e.jpg)

**Environment**
Compiler: JDK11
OS: Linux  4.19.0-arm64-desktop
Runtime : java-8-openjdk-arm64

Anyone have an idea ?

Thanks :)

**Comment by laurit** [comment]
Try running
```java
import java.security.KeyStore;
import javax.net.ssl.TrustManagerFactory;

public class Main {
    public static void main(String[] args) throws Exception {
        TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm()).init((KeyStore) null);
    }
}
```
If that also fails then it is not a problem with the agent. I would try with a different jdk.

**Comment by Stardust002** [comment]
> Try running
> 
> ```java
> import java.security.KeyStore;
> import javax.net.ssl.TrustManagerFactory;
> 
> public class Main {
>     public static void main(String[] args) throws Exception {
>         TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm()).init((KeyStore) null);
>     }
> }
> ```
> 
> If that also fails then it is not a problem with the agent. I would try with a different jdk.

Hi, laurit:

I tried this code but it still failed. then i tried other jdk like jdk11 but it seems can't work too. the error log like this:

![微信图片_20230420172300](https://user-images.githubusercontent.com/75619600/233321646-bf63c08f-e016-497e-a7d0-f4f555a28c99.jpg)

**Comment by laurit** [comment]
As this is an issue with your jvm installation we can't help you. If the jvm you use is provided by your linux distribution you may seek assistance from them. You could also try a jvm from another source such as https://adoptium.net/en-GB/temurin/releases/ or openjdk or oracle and see if it works any better. As far as I understand the issue is that you jvm truststore includes a certificate that uses a curve that jvm doesn't know about. I tried printing the list of supported curves on the jdks I use and this curve didn't show up. Googling this curve seems to indicate that this curve is used in Chinese SM2 cryptosystem. You could also run the `TrustManager` test app with `-Djavax.net.debug=all` and from the output see where the trust store location is and try removing the offending certificate.
