### ISSUE TITLE
Is the agent hosted on Maven Central?

### ISSUE THREAD

**Issue by vemv** [open-telemetry/opentelemetry-java-instrumentation#8414]
Hi! I see a series of artifacts on Maven Central, however I'm not sure if any of those corresponds to https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

It would be greatly appreciated to be able to use a standard build setup, instead of having to add bespoke steps.

Thanks - V

**Comment by trask** [comment]
yes, check out https://search.maven.org/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent

**Comment by laurit** [comment]
> Thanks! Could this be documented here?
> 
> https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/413890d246253f65831dd07bc51a38e7b19cedd8/README.md?plain=1#L64

One reason we may not wish to document this here is that we do not wish to tempt people into adding dependency to the agent into their maven builds because for most this will not work. You need to add the `opentelemetry-javaagent.jar` to jvm argumens with `-javaagent`, just adding the dependency to your project won't work. The people that know what they are doing and have valid reasons for adding dependency to the javaagent can easily find it by searching for `opentelemetry-javaagent` on central.
