### ISSUE TITLE
Unexpected non-root current context found when extracting remote context

### ISSUE THREAD

**Issue by insotriplesix** [open-telemetry/opentelemetry-java-instrumentation#8536]
**Describe the bug**

If I make a gRPC request and it goes thru the services A, B and C all connected with gRPC channels - I'll get the `Unexpected non-root current context found when extracting remote context` errors presented in all three services' logs. I don't see any problems with traces or spans in Grafana, nothing seems to be missed or invalid or corrupted or hierarchically disordered (or maybe I just don't see something wrong). But the message keeps appear in the logs request after request. The same if the request goes thru a Kafka channel.

**Steps to reproduce**

In our team, we make requests by saying something to a mobile phone, then they go to our SDK which is connected with back-end services via a gRPC channel. But I can also reproduce the error if I make the request via BloomRPC or send a message directly to a Kafka topic.

**What did you expect to see?**

I expect to see no errors in the logs.

**What did you see instead?**

I see the `Unexpected non-root current context found when extracting remote context` error message.

**What version are you using?**

1.17.0

**Environment**

Compiler: openjdk:11.0.15-slim-buster
OS: Ubuntu 20.04 (5.4.0-139-generic)

**Additional context**

I just joined to Slack's `otel-java-instrumentation` channel and tried to get some answers by typing _unexpected non-root context_ in the search bar, and it seems I'm not the only one who struggling with the problem. People asked about it since 2021 and got no answers, so I think it would be helpful if others can find some answers or tips here (if I get some, of course).

I also asked the [question](https://stackoverflow.com/questions/75722248/unexpected-non-root-current-context-found-when-extracting-remote-context) on StackOverflow, where I provided more specific information of our back-end.
Though, I already tried to add the [Library Instrumentation for gRPC](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/grpc-1.6/library) to our project and set the `OTEL_PROPAGATORS` env without success.

Finally, I have to say that I'm not the one who integrated & configured otel things, so I'm not gonna say that we have perfectly installed stuff. If I have to check something to make sure everything is OK - let me know.

**Comment by laurit** [comment]
Firstly when you are using the javaagent you don't need to separately use gRPC library instrumentation, agent already includes it. Secondly usually you need to change the propagators when you are interacting with another system that either produces on expects traces to be passed in a format different from the w3c tracecontext that is used by default.
This debugging warning is produced when context is extracted from upstream service, for example there is an incoming http request that has context propagation headers. The assumption is that at this point current thread has an empty context, if it is not then this warning is logged. Non empty context could indicate that context has leaked over from a previous request, such leakage could cause spans to be added to the previous request. This warning does not always mean that you'll get broken traces because the context from upstream service replaces the current context even if it is not empty.
To debug this we need a minimal application that reproduces the issue. From the stack overflow post it seems that when this warning is produced when receiving kafka message then the context contains a span named `CustomCoroutineDispatcher.launch` which you probably added yourself. If that is the case then you can try if this warning goes away if you don't create that span. If it does then you can also choose to ignore this warning.

**Comment by insotriplesix** [comment]
Thank you for the explanation @laurit ! Yeah, you were right, we had a `@WithSpan` annotation above our `CustomCoroutineDispatcher.launch()` function. I deleted it and now the message disappeared. Funny thing, I already read about it somewhere and tried to delete the annotation before, but it didn't work because I was testing it for gRPC. Now I checked it for Kafka and both messages are gone. Though, the gRPC thing still doesn't give up. I'll see if I can provide you something to debug, if not - I can close the issue.

It may be a silly question, but you call it as _warning_ six times and didn't call it an _error_. Shouldn't the log then be at the `WARN` level if it's not that serious and we can ignore the message?

**Comment by laurit** [comment]
I believe it is more appropriate to call it a warning because it is not printed by default. You need to either use the `otel.javaagent.debug` flag to enable agent debug logging or the `otel.javaagent.experimental.thread-propagation-debugger.enabled` flag. I don't see a good reason why it couldn't use `WARN` instead of `ERROR`.
