### ISSUE TITLE
Enforce no context/scope leaking in all tests

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#874]
Introduce a debug flag that tracks (globally) all open scopes, and at the end of every test verify that there are no open scopes.

Continue passing the `THREAD_PROPAGATION_LOCATIONS` that was introduced in #860, and log it (if available) for any open scopes, since that thread propagation is a common cause of scopes that have been left open.

**Comment by mateuszrzeszutek** [comment]
Note: there's a `StrictContextStorage` implementation in otel-java that can be used to check all scopes.
It can be enabled by setting `io.opentelemetry.context.enableStrictContext` system property to true and calling `StrictContextStorage#.ensureAllClosed()` at the end of test in the `AgentTestRunner`. Before we do that we need to have a proper support for `ForkJoinPool`, there are loads of failures in the executors module because of that.

**Comment by anuraaga** [comment]
Yeah haven't tried to enable that for fear of spending weeks fixing the tests :P But once we have this running I think we'll have pretty good confidence in the context propagation of our instrumentation

**Comment by anuraaga** [comment]
Enabled, and have some tracking issues for remaining context issues

**Comment by johnpoth** [comment]
Would be nice to make the class public

**Comment by trask** [comment]
hi @johnpoth, can you open a new issue in https://github.com/open-telemetry/opentelemetry-java where the `StrictContextStorage` class lives?
