### ISSUE TITLE
NPE on SQS ReceiveMessageRequest

### ISSUE THREAD

**Issue by frombrest** [open-telemetry/opentelemetry-java-instrumentation#8895]
Following my comment in this issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7903

**Describe the bug**
AWS SDK v2 (AsyncSQSClient) instrumented by OTEL `TracingExecutionInterceptor()` throws NPE during an attempt to receive a message from the queue.

**Steps to reproduce**
I have prepared a small example to reproduce the issue:
[https://github.com/frombrest/otel-aws-instumentation-bug](https://github.com/frombrest/otel-aws-instumentation-bug)

**What did you expect to see?**
Successful attempt to receive a message

**What did you see instead?**
Exception:
```
Caused by: java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.http.SdkHttpRequest.method()" because "httpRequest" is null
        at io.opentelemetry.instrumentation.awssdk.v2_2.AwsSdkHttpAttributesGetter.getHttpRequestMethod(AwsSdkHttpAttributesGetter.java:31) ~[opentelemetry-aws-sdk-2.2-1.27.0-alpha.jar:1.27.0-alpha]
```

**What version are you using?**
`opentelemetry-aws-sdk-2.2-1.27.0-alpha.jar:1.27.0-alpha`

**Environment**
```
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

macOS Ventura 13.4.1 (22F82)
```

**Additional context**
When SDK does ReceiveMessageRequest, it comes to TracinExecutionInterceptor i.e. calls:
```
public void afterExecution(
      Context.AfterExecution context, ExecutionAttributes executionAttributes) {
    if (SqsReceiveMessageRequestAccess.isInstance(context.request())) {
      afterConsumerResponse(executionAttributes, context.response(), context.httpResponse());
    }
```
execution call 
```
afterConsumerResponse(executionAttributes, context.response(), context.httpResponse());
```
without injecting httpRequest to the executionAttributes.
`httpRequest` is located in `context.httpRequest()` and as you can see afterConsumerResponse method does not have access to this object which means all downstream methods will have no access to `httpRequest`.

**Comment by frombrest** [comment]
@laurit  Let me know if anything else is required

**Comment by laurit** [comment]
@frombrest thanks, I think the problem is that you are using the autoconfigure https://github.com/frombrest/otel-aws-instumentation-bug/blob/bcdb448af893890156554000c4909a9594de6023/pom.xml#L61 instrumentation which automatically sets up the `TracingExecutionInterceptor` and you are also manually setting it up in https://github.com/frombrest/otel-aws-instumentation-bug/blob/bcdb448af893890156554000c4909a9594de6023/src/main/kotlin/com/otelbug/demo/AppConfiguration.kt#L51 So you end up with two `TracingExecutionInterceptor`s which breaks. You should be able work around this by not manually adding the `TracingExecutionInterceptor` or using https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/aws-sdk/aws-sdk-2.2/library instead of https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/aws-sdk/aws-sdk-2.2/library-autoconfigure
I'll try to fix it so that having two `TracingExecutionInterceptor` won't break.

**Comment by frombrest** [comment]
Indeed. The dependency name should have made me understand that nothing needs to be done...

Anyway, thank you for your help.
