### ISSUE TITLE
Log current thread id and name as span attribute

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#942]
Currently we do not include any thread info (id, name) in spans produced by the agent. This issue is a suggestion to add two new attributes to each span just before it's started:

* `thread.id` - equal to `Thread.currentThread().getId()`
* `thread.name` - equal to `Thread.currentThread().getName()`

Those two attributes could be set in the `BaseTracer#startSpan()` method (or in a method used by/closely related to that one) so that they're uniformly added to all spans produced by the Java agent.

**Comment by anuraaga** [comment]
Should we start by filing an issue in the https://github.com/open-telemetry/opentelemetry-specification repo to add semantic conventions for these? We could have an extension of some sort for these but I don't think we should add anything by default that isn't in the spec.

It's interesting that these feel like `Resource` but since they're not constant to an app will need to be span attributes.

**Comment by trask** [comment]
> Should we start by filing an issue in the https://github.com/open-telemetry/opentelemetry-specification repo to add semantic conventions for these?

👍

**Comment by iNikem** [comment]
Цунами

**Comment by trask** [comment]
I don't think we have any generic attributes (not library specific ones) that aren't in the spec?

**Comment by iNikem** [comment]
> I don't think we have any generic attributes (not library specific ones) that aren't in the spec?

A, that's true. @mateuszrzeszutek, please follow the suggestion of @anuraaga from above

**Comment by mateuszrzeszutek** [comment]
Done: https://github.com/open-telemetry/opentelemetry-specification/issues/788

**Comment by trask** [comment]
Labeled `after-ga` but we would definitely accept a PR for this any time prior to GA
