### ISSUE TITLE
Auto instrumentation with otel4s histogram custom buckets

### ISSUE THREAD

**Issue by petraroeyal** [open-telemetry/opentelemetry-java-instrumentation#9431]
### Describe the bug

I am using Otel4s and open telemetry in a Cats application for exporting metrics to Prometheus.
I had a use case where I needed to customize one of my histogram metrics for its bucket size.
I used this guide for adding the custom bucket values - https://typelevel.org/otel4s/customization/histogram-custom-buckets/index.html
Next, I needed to add tracing to otlp to my app so I added the auto instrumentation using your Java agent.
Since I added the Java agent - the service failed to boot with the error: `Could not create Prometheus HTTP server, Address already in use.`
It seems that both the Java agent and the `AutoConfiguredOpenTelemetrySdkBuilder` are trying to create a local Prometheus server, which results in the error.

### Steps to reproduce

Add histogram bucket customization to a Cats app as explained [here](https://typelevel.org/otel4s/customization/histogram-custom-buckets/index.html).
Run the app together with the Java agent.
I'm using the following command:
`java -javaagent:/tmp/opentelemetry-javaagent.jar -Dotel.java.global-autoconfigure.enabled=true -cp my-application.jar:/app/lib/* my-application.Main"`

### Expected behavior

The app is booting normally and supports both tracing and metrics exporting, including buckets customized histogram metric.

### Actual behavior

The app is failing to boot with the error: `Could not create Prometheus HTTP server, Address already in use.`

### Javaagent or library instrumentation version

v1.29.0

### Environment

**JDK**: Eclipse Adoptium 17.0.8.1+1
**OS**: Linux 5.10.133+
**otel4s-java**: 0.2.1
**opentelemetry-sdk-extension-autoconfigure**: 1.29.0
**opentelemetry-exporter-prometheus**: 1.29.0-alpha

**Comment by laurit** [comment]
Agent internally also uses `AutoConfiguredOpenTelemetrySdk` and uses the system properties/env variables from https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md for configuration. When using agent you should not configure your own opentlemetry sdk, but use the one configured by agent. You can get the sdk configured by agent with `GlobalOpenTelemetry.get()`. To customize the sdk you'll have to use an agent extension. Check out the example extension https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension The SPI you need is https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/d7f7d913cf0f5956425c536677b80cd330f0a579/examples/extension/src/main/java/com/example/javaagent/DemoAutoConfigurationCustomizerProvider.java#L35 Instead of `addTracerProviderCustomizer`use `addMeterProviderCustomizer` that will give you access to `SdkMeterProviderBuilder` that you can use to customize the views.

**Comment by petraroeyal** [comment]
Thanks.
I'm writing in Scala, and this solution requires adding additional dependencies.
I got an alternative solution from otel4s - https://github.com/typelevel/otel4s/issues/308 which uses a config file for histogram buckets customization instead of code (which configures an additional opentlemetry SDK)
