### ISSUE TITLE
gradle build and gradle check are failing

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#984]
This can be confusing for contributors, we should fix, and have them run on CI so they don't break again.

**Comment by iNikem** [comment]
@open-telemetry/java-instrumentation-approvers What is our stance on `jacocoTestCoverageVerification`? It fails on `javaagent-api` module, because a lot of classes there have very low or absent coverage. And I have no idea how to test e.g. `io.opentelemetry.javaagent.instrumentation.api.concurrent.AdviceUtils`.

**Comment by trask** [comment]
> @open-telemetry/java-instrumentation-approvers What is our stance on `jacocoTestCoverageVerification`?

Ya, our stance is not great, we aren't even running jacoco against instrumentation at all (because)
* advice is inlined, so won't get tracked (another good reason to move logic from Advice to Tracers)
* (I'm guessing) since helper classes are injected inside of transform(), jacoco won't get a chance to instrument them
